import {Fragment,useCallback,useEffect,useMemo,useState} from "react";
import {apiUrl,demoHeaders} from "../directory/DirectoryShell";
import {downloadCsv} from "../utils/csv";
import {MultiSelect} from "../components/MultiSelect";
import {SlidersHorizontal} from "lucide-react";
type Row={id:string;occurredAt:string;user:{email:string;name:string|null}|null;actorLegacy:string|null;action:string;entity:string;recordId:string|null;oldValue:unknown;newValue:unknown;result:string|null;origin:string|null};type Options={entities:string[];actions:string[];results:string[];origins:string[]};
export function AuditPage(){
 const[rows,setRows]=useState<Row[]>([]),[options,setOptions]=useState<Options>({entities:[],actions:[],results:[],origins:[]}),[entities,setEntities]=useState<string[]>([]),[actions,setActions]=useState<string[]>([]),[results,setResults]=useState<string[]>([]),[origins,setOrigins]=useState<string[]>([]),[search,setSearch]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[filtersOpen,setFiltersOpen]=useState(false),[open,setOpen]=useState<string|null>(null),[message,setMessage]=useState(""),[page,setPage]=useState(1);const pageSize=25;
 const load=useCallback(async()=>{const query=new URLSearchParams({search,from,to});const[a,b]=await Promise.all([fetch(apiUrl+"/api/audit/admin?"+query,{headers:demoHeaders}),fetch(apiUrl+"/api/audit/admin/options",{headers:demoHeaders})]);if(!a.ok||!b.ok){setMessage(a.status===403?"Solo el administrador puede consultar la auditoría.":"No se pudo cargar la auditoría.");return}setRows(await a.json());setOptions(await b.json());setPage(1)},[search,from,to]);useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);const filteredRows=useMemo(()=>rows.filter(row=>(entities.length===0||entities.includes(row.entity))&&(actions.length===0||actions.includes(row.action))&&(results.length===0||results.includes(row.result??""))&&(origins.length===0||origins.includes(row.origin??""))),[rows,entities,actions,results,origins]);const visible=useMemo(()=>filteredRows.slice((page-1)*pageSize,page*pageSize),[filteredRows,page]);const pages=Math.max(1,Math.ceil(filteredRows.length/pageSize));
 useEffect(()=>setPage(1),[entities,actions,results,origins]);
 function exportRows(){downloadCsv("auditoria-detallada.csv",["Fecha","Actor","Correo","Acción","Entidad","Registro","Resultado","Origen","Antes","Después"],filteredRows.map(x=>[x.occurredAt,x.user?.name||x.actorLegacy||"Sistema",x.user?.email,x.action,x.entity,x.recordId,x.result,x.origin,x.oldValue?JSON.stringify(x.oldValue):"",x.newValue?JSON.stringify(x.newValue):""]))}
 return <main className="min-h-screen bg-slate-100 text-slate-950"><div className="mx-auto max-w-7xl px-5 py-8"><div className="flex justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Control</p><h1 className="mt-2 text-3xl font-bold">Auditoría</h1><p className="mt-3 text-slate-600">Consulta los cambios registrados. Esta información es de solo lectura.</p></div><button onClick={exportRows} className="h-fit rounded-xl border border-emerald-600 px-4 py-2 font-bold text-emerald-700">Exportar</button></div>
 <section className="mt-6 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={()=>setFiltersOpen(!filtersOpen)} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold"><SlidersHorizontal size={16}/>Filtros{(entities.length+actions.length+results.length+origins.length+(search?1:0)+(from?1:0)+(to?1:0))>0&&<span className="rounded-full bg-red-50 px-2 py-0.5 text-xs text-red-700">{entities.length+actions.length+results.length+origins.length+(search?1:0)+(from?1:0)+(to?1:0)}</span>}</button><span className="text-sm text-slate-500">Filtra movimientos, responsable o período.</span>{(entities.length+actions.length+results.length+origins.length+(search?1:0)+(from?1:0)+(to?1:0))>0&&<button type="button" onClick={()=>{setEntities([]);setActions([]);setResults([]);setOrigins([]);setSearch("");setFrom("");setTo("")}} className="text-sm font-bold text-red-700">Limpiar filtros</button>}</div>{filtersOpen&&<div className="mt-4 grid gap-4 border-t pt-4 md:grid-cols-4"><MultiSelect label="Entidades" emptyLabel="Todas las entidades" value={entities} onChange={setEntities} options={options.entities.map(value=>({id:value,label:value}))}/><MultiSelect label="Acciones" emptyLabel="Todas las acciones" value={actions} onChange={setActions} options={options.actions.map(value=>({id:value,label:value}))}/><MultiSelect label="Resultados" emptyLabel="Todos los resultados" value={results} onChange={setResults} options={options.results.map(value=>({id:value,label:value}))}/><MultiSelect label="Orígenes" emptyLabel="Todos los orígenes" value={origins} onChange={setOrigins} options={options.origins.map(value=>({id:value,label:value}))}/><label className="text-sm font-semibold">Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-base font-normal"/></label><label className="text-sm font-semibold">Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-base font-normal"/></label><label className="text-sm font-semibold md:col-span-2">Buscar<input value={search} onChange={e=>setSearch(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-base font-normal" placeholder="Actor, correo, entidad o registro"/></label></div>}</section>{message&&<p className="mt-5 rounded-xl bg-rose-50 px-4 py-3 font-semibold text-rose-900">{message}</p>}
 <div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50"><tr><th className="px-5 py-4">Fecha</th><th className="px-5 py-4">Actor</th><th className="px-5 py-4">Movimiento</th><th className="px-5 py-4">Registro</th><th/></tr></thead><tbody>{visible.map(row=><Fragment key={row.id}><tr className="border-t"><td className="whitespace-nowrap px-5 py-4">{new Date(row.occurredAt).toLocaleString("es-PE")}</td><td className="px-5 py-4">{row.user?.name||row.user?.email||row.actorLegacy||"Sistema"}</td><td className="px-5 py-4"><strong>{row.action}</strong><br/><span className="text-sm text-slate-500">{row.entity}</span></td><td className="px-5 py-4 font-mono text-sm">{row.recordId||"—"}</td><td className="px-5 py-4"><button onClick={()=>setOpen(open===row.id?null:row.id)} className="rounded-lg border px-3 py-2 text-sm font-bold">{open===row.id?"Ocultar":"Detalle"}</button></td></tr>{open===row.id&&<tr className="border-t bg-slate-50"><td colSpan={5} className="p-5"><div className="grid gap-4 lg:grid-cols-2"><Value title="Antes" value={row.oldValue}/><Value title="Después" value={row.newValue}/></div></td></tr>}</Fragment>)}</tbody></table></div><Pager page={page} pages={pages} setPage={setPage}/><p className="mt-3 text-sm text-slate-500">{filteredRows.length} movimientos según los filtros seleccionados.</p></div></main>}
function Value({title,value}:{title:string;value:unknown}){return <div><h3 className="font-bold">{title}</h3><pre className="mt-2 max-h-80 overflow-auto rounded-xl bg-slate-900 p-4 text-xs text-slate-100">{value?JSON.stringify(value,null,2):"Sin valor"}</pre></div>}
function Pager({page,pages,setPage}:{page:number;pages:number;setPage:(page:number)=>void}){return <div className="mt-4 flex items-center justify-end gap-3"><button disabled={page===1} onClick={()=>setPage(page-1)} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Anterior</button><span className="text-sm font-semibold">Página {page} de {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Siguiente</button></div>}
