packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "prisma"
allowBuilds:
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  esbuild: true
  prisma: true
