import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { PrismaService } from "../database/prisma.service";

type MaturityCommunicationType = "OPENING" | "REMINDER";

@Injectable()
export class CommunicationsRepository {
  constructor(private readonly prisma: PrismaService) {}
  private render(template:string,variables:Record<string,unknown>){return template.replace(/\{\{(\w+)\}\}/g,(_,key)=>variables[key]===null||variables[key]===undefined?"":String(variables[key]))}
  private escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!))}
  private renderPendingCoursesByModule(courses:Array<{name:string;module:string;roles:Set<string>}>){const modules=new Map<string,typeof courses>();for(const course of courses)modules.set(course.module,[...(modules.get(course.module)??[]),course]);return[...modules.entries()].sort(([left],[right])=>left.localeCompare(right,"es",{numeric:true})).map(([module,items])=>`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:0 0 18px;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><tr><td style="padding:13px 16px;background:#351414;color:#fff"><strong style="font-size:14px">${this.escapeHtml(module)}</strong><span style="float:right;font-size:12px;color:#a5f3fc">${items.length} pendiente${items.length===1?"":"s"}</span></td></tr>${items.sort((a,b)=>a.name.localeCompare(b.name,"es")).map((course,index)=>`<tr><td style="padding:14px 16px;${index<items.length-1?"border-bottom:1px solid #e2e8f0;":""}"><div style="font-size:14px;font-weight:700;color:#172033">${index+1}. ${this.escapeHtml(course.name)}</div><div style="margin-top:5px;font-size:12px;line-height:18px;color:#64748b">Rol${course.roles.size===1?"":"es"}: ${this.escapeHtml([...course.roles].sort().join(", "))}</div></td></tr>`).join("")}</table>`).join("")}

  private async candidates(periodId:string,type:MaturityCommunicationType){
    const period=await this.prisma.period.findUnique({where:{id:periodId},include:{status:true}});
    if(!period)throw new NotFoundException("No se encontró el período");
    if(period.status.code!=="AUTOEVALUACION")throw new BadRequestException("Las comunicaciones solo pueden prepararse mientras la autoevaluación está abierta");
    const[assignments,submitted]=await Promise.all([this.prisma.personRole.findMany({where:{status:{code:"ACTIVO"},developmentPathMode:"STANDARD",role:{observableBehaviors:{some:{active:true,behavior:{active:true,dimension:{active:true}}}}}},include:{person:true,role:true,team:true},orderBy:[{team:{sourceId:"asc"}},{person:{names:"asc"}}]}),this.prisma.roleSelfAssessment.findMany({where:{periodId},select:{personId:true,roleId:true}})]);
    const submittedKeys=new Set(submitted.map(item=>`${item.personId}|${item.roleId}`)),groups=new Map<string,(typeof assignments)>();for(const item of assignments){const key=`${item.personId}|${item.roleId}`;groups.set(key,[...(groups.get(key)??[]),item])}const unique=[...groups.entries()].filter(([key])=>type!=="REMINDER"||!submittedKeys.has(key)).map(([,items])=>({...items[0],teams:items.map(item=>item.team)}));
    return{period,assignments:unique};
  }

  async preview(periodId:string,type:MaturityCommunicationType){const {period,assignments}=await this.candidates(periodId,type);return{period:{id:period.id,name:period.name,status:period.status.code},type,total:assignments.length,withEmail:assignments.filter(x=>x.person.email).length,withoutEmail:assignments.filter(x=>!x.person.email).length,recipients:assignments.slice(0,100).map(x=>({personRoleId:x.id,person:x.person.names,email:x.person.email,role:x.role.name,team:x.teams.map(team=>team.sourceId).join(", ")}))}}

  async prepareMaturity(periodId:string,type:MaturityCommunicationType,requestedById:string){const {period,assignments}=await this.candidates(periodId,type);const eventType=type==="OPENING"?"SELF_ASSESSMENT_OPENED":"SELF_ASSESSMENT_REMINDER";const template=await this.prisma.communicationTemplate.findFirst({where:{code:eventType,active:true}});if(!template)throw new BadRequestException(`La plantilla ${eventType} no existe o está inactiva`);const day=new Date().toISOString().slice(0,10);const rows=assignments.map(item=>{const teamCode=item.teams.map(team=>team.sourceId).join(", "),variables={personName:item.person.names,roleName:item.role.name,teamCode,periodName:period.name,closesAt:period.selfAssessmentClosesAt?.toISOString()??null};return{eventType,recipient:item.person.email,subject:this.render(template.subjectTemplate,variables),templateCode:eventType,variables,status:item.person.email?"PENDIENTE":"OMITIDA_SIN_CORREO",source:"MANUAL_ADMIN",dedupeKey:`${eventType}:${period.id}:${item.personId}:${item.roleId}:${type==="REMINDER"?day:"OPENING"}`,personRoleId:item.id,periodId:period.id,requestedById}});const result=rows.length?await this.prisma.communication.createMany({data:rows,skipDuplicates:true}):{count:0};await this.prisma.audit.create({data:{occurredAt:new Date(),userId:requestedById,action:"PREPARE_COMMUNICATIONS",entity:"MATURITY_PERIOD",recordId:periodId,newValue:{eventType,candidates:rows.length,created:result.count},result:"OK",origin:"WEB"}});return{eventType,candidates:rows.length,created:result.count,skipped:rows.length-result.count,withoutEmail:rows.filter(x=>!x.recipient).length}}

  async list(status?:string,page=1,pageSize=25){page=Math.max(1,page);pageSize=Math.min(100,Math.max(1,pageSize));const where={status:status||undefined};const[total,items]=await Promise.all([this.prisma.communication.count({where}),this.prisma.communication.findMany({where,skip:(page-1)*pageSize,take:pageSize,orderBy:{createdAt:"desc"},include:{personRole:{include:{person:true,role:true,team:true}},period:true,requestedBy:{select:{name:true,email:true}}}})]);return{items,total,page,pageSize,pages:Math.max(1,Math.ceil(total/pageSize))}}

  async deliverPending(limit:number,userId:string|null,send:(message:{communicationId:string;dedupeKey:string;to:string;subject:string;text:string})=>Promise<unknown>,communicationId?:string,maxAttempts=3){
    const now=new Date();
    const rows=await this.prisma.communication.findMany({where:{id:communicationId,recipient:{not:null},OR:[{status:"PENDIENTE"},{status:"REINTENTO",nextAttemptAt:{lte:now}}]},orderBy:{createdAt:"asc"},take:limit,include:{personRole:{include:{team:true}}}});
    const templates=await this.prisma.communicationTemplate.findMany({where:{code:{in:[...new Set(rows.map(row=>row.templateCode))]},active:true}}),byCode=new Map(templates.map(template=>[template.code,template]));let sent=0,failed=0,skipped=0;
    for(const row of rows){const attemptCount=row.attemptCount+1,claimed=await this.prisma.communication.updateMany({where:{id:row.id,status:{in:["PENDIENTE","REINTENTO"]}},data:{status:"EN_PROCESO",errorSummary:null,attemptCount,lastAttemptAt:now,lockedAt:now}});if(!claimed.count){skipped++;continue}const template=byCode.get(row.templateCode);if(!template){await this.prisma.communication.update({where:{id:row.id},data:{status:"FALLIDA",lockedAt:null,errorSummary:`La plantilla ${row.templateCode} no existe o está inactiva`}});failed++;continue}try{const variables={...((row.variables??{}) as Record<string,unknown>),teamName:row.personRole?.team.name??"",assignedAt:row.personRole?.startDate?.toLocaleDateString("es-PE",{timeZone:"UTC"})??""},text=this.render(template.bodyTemplate,variables),subject=this.render(row.subject,variables);await send({communicationId:row.id,dedupeKey:row.dedupeKey,to:row.recipient!,subject,text});await this.prisma.communication.update({where:{id:row.id},data:{status:"ENVIADA",sentAt:new Date(),errorSummary:null,lockedAt:null,nextAttemptAt:null}});sent++}catch(error){const message=error instanceof Error?error.message:String(error),retry=attemptCount<maxAttempts;await this.prisma.communication.update({where:{id:row.id},data:{status:retry?"REINTENTO":"FALLIDA",errorSummary:message.slice(0,500),lockedAt:null,nextAttemptAt:retry?new Date(now.getTime()+24*60*60*1000):null}});failed++}}
    await this.prisma.audit.create({data:{occurredAt:new Date(),userId,action:"SEND_PENDING_COMMUNICATIONS",entity:"COMMUNICATION",recordId:"BATCH",newValue:{provider:"GOOGLE_APPS_SCRIPT",requested:rows.length,sent,failed,skipped},result:failed?"PARTIAL":"OK",origin:"WEB"}});return{requested:rows.length,sent,failed,skipped}
  }

  async recoverStale(){const threshold=new Date(Date.now()-30*60*1000);return this.prisma.communication.updateMany({where:{status:"EN_PROCESO",lockedAt:{lt:threshold}},data:{status:"REINTENTO",lockedAt:null,nextAttemptAt:new Date(),errorSummary:"Proceso anterior interrumpido; reintento programado"}})}

  async prepareCourseReminders(dateKey:string,recipientEmail?:string,dedupeSuffix=""){
    const template=await this.prisma.communicationTemplate.findFirst({where:{code:"COURSE_PENDING_REMINDER",active:true}});if(!template)throw new BadRequestException("La plantilla COURSE_PENDING_REMINDER no existe o está inactiva");
    const rows=await this.prisma.personCourse.findMany({where:{personRole:{status:{code:"ACTIVO"},developmentPathMode:"STANDARD",person:{status:{code:"ACTIVO"},email:recipientEmail}},course:{status:{code:"ACTIVO"}}},include:{status:true,course:{include:{module:true}},personRole:{include:{person:true,role:true}}},orderBy:[{personRole:{person:{names:"asc"}}},{course:{name:"asc"}}]});
    const completed=new Set(["TERMINADO","APROBADO","COMPLETADO"]),groups=new Map<string,typeof rows>();for(const row of rows)groups.set(row.personRole.personId,[...(groups.get(row.personRole.personId)??[]),row]);
    const start=new Date(`${dateKey}T00:00:00-05:00`),end=new Date(start.getTime()+24*60*60*1000),recentRoleEvents=await this.prisma.communication.findMany({where:{eventType:{in:["ROLE_ASSIGNED","ROLE_REACTIVATED"]},createdAt:{gte:start,lt:end},personRoleId:{not:null}},select:{personRole:{select:{personId:true}}}}),suppressed=new Set(recentRoleEvents.flatMap(item=>item.personRole?[item.personRole.personId]:[]));
    if(recipientEmail)suppressed.clear();
    const communications=[] as Prisma.CommunicationCreateManyInput[];
    for(const[personId,items]of groups){
      if(suppressed.has(personId))continue;
      const courses=new Map<string,{name:string;module:string;roles:Set<string>;done:boolean}>();
      for(const item of items){const current=courses.get(item.courseId)??{name:item.course.name,module:item.course.module.name,roles:new Set<string>(),done:false};current.roles.add(item.personRole.role.name);current.done=current.done||completed.has(item.status.code);courses.set(item.courseId,current)}
      const all=[...courses.values()],pending=all.filter(course=>!course.done);if(!pending.length)continue;
      const person=items[0].personRole.person,pendingCoursesHtml=this.renderPendingCoursesByModule(pending),completedCourses=all.length-pending.length,progressPercent=all.length?Math.round(completedCourses*100/all.length):0,variables={personName:person.names,totalCourses:all.length,completedCourses,pendingCourses:pending.length,progressPercent,pendingCoursesHtml,generatedAt:dateKey};
      communications.push({eventType:"COURSE_PENDING_REMINDER",recipient:person.email,subject:this.render(template.subjectTemplate,variables),templateCode:template.code,variables:variables as Prisma.InputJsonObject,status:person.email?"PENDIENTE":"OMITIDA_SIN_CORREO",source:dedupeSuffix?"MANUAL_ADMIN":"AUTOMATICA",dedupeKey:`COURSE_PENDING_REMINDER:${personId}:${dateKey}${dedupeSuffix}`,personRoleId:items[0].personRoleId})
    }
    const result=communications.length?await this.prisma.communication.createMany({data:communications,skipDuplicates:true}):{count:0};await this.prisma.audit.create({data:{occurredAt:new Date(),action:"PREPARE_COURSE_REMINDERS",entity:"COMMUNICATION",recordId:dateKey,newValue:{candidates:communications.length,created:result.count,suppressedByRoleEvent:suppressed.size,withoutEmail:communications.filter(item=>!item.recipient).length},result:"OK",origin:"SYSTEM"}});return{candidates:communications.length,created:result.count}
  }

  async cleanupCourseReminders(retentionDays=30){const threshold=new Date(Date.now()-retentionDays*24*60*60*1000),result=await this.prisma.communication.deleteMany({where:{eventType:"COURSE_PENDING_REMINDER",status:{in:["ENVIADA","OMITIDA_SIN_CORREO"]},OR:[{sentAt:{lt:threshold}},{sentAt:null,createdAt:{lt:threshold}}]}});await this.prisma.audit.create({data:{occurredAt:new Date(),action:"CLEANUP_COURSE_REMINDERS",entity:"COMMUNICATION",recordId:threshold.toISOString(),newValue:{retentionDays,deleted:result.count},result:"OK",origin:"SYSTEM"}});return result}

  listTemplates(){return this.prisma.communicationTemplate.findMany({orderBy:{name:"asc"}})}
  async updateTemplate(id:string,input:{name?:string;subjectTemplate?:string;bodyTemplate?:string;senderName?:string;senderEmail?:string;active?:boolean},userId:string){const current=await this.prisma.communicationTemplate.findUnique({where:{id}});if(!current)throw new NotFoundException("No se encontró la plantilla");const required=[input.name,input.subjectTemplate,input.bodyTemplate,input.senderName,input.senderEmail];if(required.some(value=>typeof value!=="string"||!value.trim()))throw new BadRequestException("Nombre, asunto, contenido y remitente son obligatorios");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.senderEmail!))throw new BadRequestException("El correo del remitente no es válido");return this.prisma.$transaction(async tx=>{const updated=await tx.communicationTemplate.update({where:{id},data:{name:input.name!.trim(),subjectTemplate:input.subjectTemplate!.trim(),bodyTemplate:input.bodyTemplate!.trim(),senderName:input.senderName!.trim(),senderEmail:input.senderEmail!.trim().toLowerCase(),active:input.active??current.active}});await tx.audit.create({data:{occurredAt:new Date(),userId,action:"UPDATE",entity:"COMMUNICATION_TEMPLATE",recordId:id,oldValue:current,newValue:updated,result:"OK",origin:"WEB"}});return updated})}
}
