import { BadRequestException, Injectable, ServiceUnavailableException } from "@nestjs/common";

type SendEmail={to:string;subject:string;text:string;html?:string;replyTo?:string};

@Injectable()
export class GmailService {
  // PENDIENTE GOOGLE/TI (puntos 1-5): mantener en false hasta habilitar Gmail API,
  // crear OAuth, autorizar la cuenta remitente y aprobar el envío controlado.
  private readonly deliveryImplementationEnabled = false;
  private required(name:string){const value=process.env[name]?.trim();if(!value)throw new ServiceUnavailableException(`Falta configurar ${name}`);return value}
  status(){const keys=["GOOGLE_GMAIL_CLIENT_ID","GOOGLE_GMAIL_CLIENT_SECRET","GOOGLE_GMAIL_REFRESH_TOKEN","GOOGLE_GMAIL_SENDER_EMAIL"];const missing=keys.filter(key=>!process.env[key]?.trim());return{provider:"GMAIL_API",enabled:this.deliveryImplementationEnabled&&process.env.GOOGLE_GMAIL_ENABLED==="true",configured:missing.length===0,blockedUntilOAuth:!this.deliveryImplementationEnabled,missing,senderName:process.env.GOOGLE_GMAIL_SENDER_NAME??"Oficina Transformación",senderEmail:process.env.GOOGLE_GMAIL_SENDER_EMAIL??"oficinatransformacion@danper.com",transport:"HTTPS"}}
  private async accessToken(){const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:this.required("GOOGLE_GMAIL_CLIENT_ID"),client_secret:this.required("GOOGLE_GMAIL_CLIENT_SECRET"),refresh_token:this.required("GOOGLE_GMAIL_REFRESH_TOKEN"),grant_type:"refresh_token"})});const body=await response.json() as {access_token?:string;error_description?:string};if(!response.ok||!body.access_token)throw new ServiceUnavailableException(body.error_description??"Google no entregó un token de acceso");return body.access_token}
  async send(input:SendEmail){if(!this.deliveryImplementationEnabled||process.env.GOOGLE_GMAIL_ENABLED!=="true")throw new ServiceUnavailableException("El envío por Gmail está bloqueado hasta completar la autorización de TI y OAuth");if(!/^\S+@\S+\.\S+$/.test(input.to))throw new BadRequestException("Destinatario inválido");const senderEmail=this.required("GOOGLE_GMAIL_SENDER_EMAIL"),senderName=process.env.GOOGLE_GMAIL_SENDER_NAME?.trim()||"Oficina Transformación";const boundary=`mochelab-${Date.now()}`;const headers=[`From: ${senderName} <${senderEmail}>`,`To: ${input.to}`,`Subject: =?UTF-8?B?${Buffer.from(input.subject).toString("base64")}?=`,input.replyTo?`Reply-To: ${input.replyTo}`:null,"MIME-Version: 1.0",`Content-Type: multipart/alternative; boundary=\"${boundary}\"`].filter(Boolean);const parts=[`--${boundary}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${input.text}`,input.html?`--${boundary}\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n${input.html}`:null,`--${boundary}--`].filter(Boolean);const raw=Buffer.from(`${headers.join("\r\n")}\r\n\r\n${parts.join("\r\n")}`).toString("base64url");const token=await this.accessToken();const response=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({raw})});const body=await response.json() as {id?:string;threadId?:string;error?:{message?:string}};if(!response.ok||!body.id)throw new ServiceUnavailableException(body.error?.message??"Gmail no pudo enviar el mensaje");return{id:body.id,threadId:body.threadId}}
}
