import { useEffect, useState } from "react";
import { apiUrl, demoHeaders } from "../directory/DirectoryShell";
import { Scale } from "lucide-react";
import { ConfirmationDialog } from "../components/ConfirmationDialog";

type Detail={id:string;personId:string;person:string;role:string;team:string;period:string;originalScore:number;calibratedScore:number|null;calibratedAt:string|null;calibrationComments:string|null;responses:{behaviorId:string;statement:string;score:number;comments:string|null;dimensionName:string}[];people:{id:string;names:string}[];officialTeamMaturities:{id:string}[]};

export function CalibrationPage(){
 const id=new URLSearchParams(location.search).get("id"),[data,setData]=useState<Detail|null>(null),[score,setScore]=useState(0),[comments,setComments]=useState(""),[message,setMessage]=useState(""),[confirming,setConfirming]=useState(false),[saving,setSaving]=useState(false),[confirmError,setConfirmError]=useState("");
 const [training,setTraining]=useState(false),[trainedPersonId,setTrainedPersonId]=useState(""),[trainingEvidence,setTrainingEvidence]=useState(""),[camp,setCamp]=useState(false),[campName,setCampName]=useState(""),[campDate,setCampDate]=useState(""),[campEvidence,setCampEvidence]=useState("");
 useEffect(()=>{if(!id){setMessage("Selecciona una autoevaluación desde la bandeja.");return}fetch(`${apiUrl}/api/maturity/admin/calibrations/${id}`,{headers:demoHeaders}).then(async response=>{if(!response.ok)throw new Error("No se pudo cargar la calibración");return response.json() as Promise<Detail>}).then(item=>{setData(item);setScore(item.calibratedScore??item.originalScore);setComments(item.calibrationComments??"")}).catch((error:Error)=>setMessage(error.message))},[id]);
 if(!data)return <main className="min-h-screen bg-slate-100 p-8">{message||"Cargando calibración…"}</main>;
 const readonly=Boolean(data.calibratedAt),official=score>=1.5,changed=score!==data.originalScore,wantsMastery=training||camp;
 const masteryComplete=training&&Boolean(trainedPersonId)&&Boolean(trainingEvidence.trim())&&camp&&Boolean(campName.trim())&&Boolean(campDate)&&Boolean(campEvidence.trim())&&data.officialTeamMaturities.length>0;
 const valid=!readonly&&score>=0&&score<=2&&(!changed||Boolean(comments.trim()))&&(!wantsMastery||masteryComplete);
 async function save(){if(!valid)return;setSaving(true);setConfirmError("");const mastery=masteryComplete?{trainedPersonId,trainingEvidence:trainingEvidence.trim(),trainingVerified:true,campVerified:true,campName:campName.trim(),campDate,campEvidence:campEvidence.trim(),teamMaturityId:data!.officialTeamMaturities[0].id}:undefined;try{const response=await fetch(`${apiUrl}/api/maturity/admin/calibrations/${data!.id}`,{method:"PATCH",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify({calibratedScore:score,comments:comments||undefined,mastery})});const body=await response.json().catch(()=>({}));if(response.ok){setData({...data!,calibratedScore:score,calibratedAt:new Date().toISOString(),calibrationComments:comments});setMessage(`Calibración guardada. Nivel final: ${body.level}.`);setConfirming(false)}else setConfirmError(body.message??"No se pudo guardar la calibración")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl justify-between px-5 py-4"><a href="/madurez/calibraciones" className="font-bold">← Calibraciones</a><b>Administrador</b></div></header><div className="mx-auto max-w-7xl px-5 py-8"><h1 className="text-3xl font-bold">Revisión y calibración</h1><p className="mt-2 text-slate-600">{data.person} · {data.role} · {data.team} · {data.period}</p><div className="mt-8 grid gap-7 2xl:grid-cols-[minmax(0,1fr)_22rem]"><section className="space-y-5"><article className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Respuestas originales</h2>{data.responses.map(item=><div key={item.behaviorId} className="mt-4 border-t pt-4"><p className="text-sm font-semibold text-emerald-700">{item.dimensionName}</p><p className="mt-1">{item.statement}</p><p className="mt-2 font-bold">Puntaje: {item.score}</p>{item.comments&&<p className="text-sm text-slate-500">{item.comments}</p>}</div>)}</article>
 {official&&<article className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Condiciones para Maestro</h2><p className="mt-2 text-sm text-slate-600">Se muestran porque el puntaje calibrado alcanzó Oficial. Para Maestro deben cumplirse y documentarse las tres.</p><label className="mt-4 flex gap-3"><input type="checkbox" checked={training} onChange={event=>setTraining(event.target.checked)}/>Ha formado a una persona</label>{training&&<div className="mt-2 grid gap-2"><select value={trainedPersonId} onChange={event=>setTrainedPersonId(event.target.value)} className="rounded-xl border p-3"><option value="">Selecciona la persona formada</option>{data.people.map(person=><option key={person.id} value={person.id}>{person.names}</option>)}</select><textarea value={trainingEvidence} onChange={event=>setTrainingEvidence(event.target.value)} placeholder="Evidencia o detalle de la formación" className="rounded-xl border p-3"/></div>}<label className="mt-4 flex gap-3"><input type="checkbox" checked={camp} onChange={event=>setCamp(event.target.checked)}/>Ha facilitado un campamento</label>{camp&&<div className="mt-2 grid gap-2 sm:grid-cols-2"><input value={campName} onChange={event=>setCampName(event.target.value)} placeholder="Nombre del campamento" className="rounded-xl border p-3"/><input type="date" max={new Date().toISOString().slice(0,10)} value={campDate} onChange={event=>setCampDate(event.target.value)} className="rounded-xl border p-3"/><textarea value={campEvidence} onChange={event=>setCampEvidence(event.target.value)} placeholder="Evidencia o detalle del campamento" className="rounded-xl border p-3 sm:col-span-2"/></div>}<p className={`mt-4 rounded-xl p-3 text-sm font-semibold ${data.officialTeamMaturities.length?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{data.officialTeamMaturities.length?"✓ El equipo está en nivel Oficial":"El equipo aún no está en nivel Oficial"}</p></article>}
 <article className="rounded-2xl bg-white p-5 shadow-sm"><label className="font-bold">Comentario de calibración<textarea rows={5} value={comments} onChange={event=>setComments(event.target.value)} className="mt-3 w-full rounded-xl border p-3 font-normal" placeholder="Obligatorio si cambias el puntaje"/></label></article></section><aside><div className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-sm text-emerald-400">Puntaje enviado</p><p className="text-4xl font-bold">{data.originalScore.toFixed(2)}</p><label className="mt-6 block text-sm text-emerald-400">Puntaje calibrado<input type="number" min="0" max="2" step=".01" value={score} onChange={event=>setScore(Number(event.target.value))} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-900 p-3 text-3xl font-bold"/></label><button disabled={!valid} onClick={()=>{setConfirmError("");setConfirming(true)}} className="mt-6 w-full rounded-xl bg-emerald-500 p-3 font-bold text-slate-950 disabled:bg-slate-700">Guardar calibración</button></div>{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-4 font-semibold text-emerald-900">{message}</p>}</aside></div></div>{confirming&&<ConfirmationDialog title="Confirmar calibración final" description="Este resultado quedará cerrado para el período seleccionado." icon={<Scale size={20}/>} confirmLabel="Guardar resultado final" busy={saving} error={confirmError} onClose={()=>setConfirming(false)} onConfirm={()=>void save()}><div className="rounded-xl bg-slate-50 p-4"><strong>{data.person}</strong><span className="mt-1 block text-sm text-slate-500">{data.role} · {data.team} · {data.period}</span></div><dl className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border p-3"><dt className="text-xs font-bold uppercase text-slate-500">Puntaje enviado</dt><dd className="mt-1 text-2xl font-bold">{data.originalScore.toFixed(2)}</dd></div><div className="rounded-xl border p-3"><dt className="text-xs font-bold uppercase text-slate-500">Puntaje final</dt><dd className="mt-1 text-2xl font-bold">{score.toFixed(2)}</dd></div></dl><p className="mt-4 text-sm text-slate-700">Después de guardar, la calibración no podrá modificarse.</p></ConfirmationDialog>}</main>;
}
