import { useCallback, useEffect, useState } from "react";
import { apiUrl, demoHeaders } from "../directory/DirectoryShell";

type Status = "PLANIFICADO" | "AUTOEVALUACION" | "CALIBRACION" | "CERRADO" | "CANCELADO";
type Period = { id:string; code:string; name:string; startDate:string; endDate:string; selfAssessmentOpensAt:string|null; selfAssessmentClosesAt:string|null; calibrationClosesAt:string|null; configurationVersion:string; status:{code:Status;name:string}; _count:{selfAssessments:number;roleMaturities:number};summary:{eligibleRoles:number;submitted:number;pendingSubmission:number;calibrated:number;pendingCalibration:number} };
type Form = { code:string; name:string; startDate:string; endDate:string; selfAssessmentOpensAt:string; selfAssessmentClosesAt:string; calibrationClosesAt:string; configurationVersion:string };
const empty:Form={code:"",name:"",startDate:"",endDate:"",selfAssessmentOpensAt:"",selfAssessmentClosesAt:"",calibrationClosesAt:"",configurationVersion:""};
const styles:Record<Status,string>={PLANIFICADO:"bg-slate-100 text-slate-700",AUTOEVALUACION:"bg-sky-100 text-sky-800",CALIBRACION:"bg-amber-100 text-amber-800",CERRADO:"bg-emerald-100 text-emerald-800",CANCELADO:"bg-rose-100 text-rose-800"};
const next:Partial<Record<Status,Status>>={PLANIFICADO:"AUTOEVALUACION",AUTOEVALUACION:"CALIBRACION",CALIBRACION:"CERRADO"};
const actions:Partial<Record<Status,string>>={PLANIFICADO:"Abrir autoevaluación",AUTOEVALUACION:"Iniciar calibración",CALIBRACION:"Cerrar período"};
const date=(value:string)=>new Date(value).toLocaleDateString("es-PE",{day:"2-digit",month:"short",year:"numeric"});
const datetime=(value:string|null)=>value?new Date(value).toLocaleString("es-PE",{dateStyle:"medium",timeStyle:"short"}):"Sin configurar";
const fields:[keyof Form,string,string,string][]=[
 ["code","Código","2027-1","text"],["name","Nombre","Primer semestre 2027","text"],
 ["startDate","Fecha inicial","","date"],["endDate","Fecha final","","date"],
 ["selfAssessmentOpensAt","Apertura de autoevaluación","","datetime-local"],
 ["selfAssessmentClosesAt","Cierre de autoevaluación","","datetime-local"],
 ["calibrationClosesAt","Cierre de calibración","","datetime-local"],
 ["configurationVersion","Versión del formulario","2027-1-v1","text"],
];

export function MaturityPeriodsPage(){
 const [periods,setPeriods]=useState<Period[]>([]);
 const [form,setForm]=useState<Form>(empty);
 const [show,setShow]=useState(false);
 const [busy,setBusy]=useState(false);
 const [message,setMessage]=useState("");
 const load=useCallback(async()=>{setBusy(true);try{const r=await fetch(`${apiUrl}/api/maturity/admin/periods`,{headers:demoHeaders});if(!r.ok)throw new Error("No se pudieron cargar los períodos");setPeriods(await r.json())}catch(e){setMessage(e instanceof Error?e.message:"Error inesperado")}finally{setBusy(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const set=(field:keyof Form,value:string)=>setForm(current=>({...current,[field]:value}));
 async function create(){setBusy(true);setMessage("");const r=await fetch(`${apiUrl}/api/maturity/admin/periods`,{method:"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(typeof body.message==="string"?body.message:"No se pudo crear el período");setBusy(false);return}setMessage("Período creado como Planificado.");setForm(empty);setShow(false);await load()}
 async function advance(period:Period){const status=next[period.status.code];if(!status)return;if(!window.confirm(`¿Confirmas avanzar el período a ${status}? Este cambio controla quién puede responder o calibrar.`))return;setBusy(true);setMessage("");const r=await fetch(`${apiUrl}/api/maturity/admin/periods/${period.id}/status`,{method:"PATCH",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify({status})});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(typeof body.message==="string"?body.message:"No se pudo cambiar el estado");setBusy(false);return}setMessage(`Período actualizado: ${body.status.name}.`);await load()}
 async function communicate(period:Period,type:"OPENING"|"REMINDER"){setBusy(true);setMessage("");try{const previewResponse=await fetch(`${apiUrl}/api/communications/maturity/${period.id}/preview?type=${type}`,{headers:demoHeaders});const preview=await previewResponse.json();if(!previewResponse.ok)throw new Error(preview.message??"No se pudo preparar la comunicación");const label=type==="OPENING"?"la apertura":"el recordatorio";if(!window.confirm(`Se preparará ${label} para ${preview.withEmail} persona(s). ${preview.withoutEmail} no tienen correo y quedarán identificadas. ¿Continuar?`))return;const response=await fetch(`${apiUrl}/api/communications/maturity/${period.id}`,{method:"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify({type})});const result=await response.json();if(!response.ok)throw new Error(result.message??"No se pudo preparar la comunicación");setMessage(`${result.created} comunicación(es) generadas. ${result.skipped} ya existían.`)}catch(error){setMessage(error instanceof Error?error.message:"Error inesperado")}finally{setBusy(false)}}
 const valid=Object.values(form).every(value=>value.trim());
 return <main className="min-h-screen bg-slate-100 text-slate-950">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="/" className="text-lg font-bold">Mochelab <span className="text-emerald-600">2.0</span></a><span className="rounded-full bg-slate-900 px-3 py-1 text-sm font-semibold text-white">Administrador</span></div></header>
  <div className="mx-auto max-w-6xl px-5 py-8 lg:px-8">
   <div className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-7 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Configuración de madurez</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Períodos de evaluación</h1><p className="mt-3 text-base text-slate-600">Administra el ciclo completo de autoevaluación y calibración.</p></div><button onClick={()=>{setShow(true);setMessage("")}} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white">Nuevo período</button></div>
   {show&&<section className="mt-6 rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Nuevo período</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map(([field,label,placeholder,type])=><label key={field} className="text-sm font-semibold">{label}<input type={type} value={form[field]} onChange={e=>set(field,e.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600"/></label>)}</div><p className="mt-4 text-sm text-slate-500">Se guardará como Planificado. Las fechas y la versión quedarán congeladas para este ciclo.</p><div className="mt-5 flex justify-end gap-3"><button onClick={()=>setShow(false)} className="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600">Cancelar</button><button disabled={!valid||busy} onClick={create} className="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-bold text-white disabled:bg-slate-300">Crear período</button></div></section>}
   {message&&<p role="status" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900">{message}</p>}
   <div className="mt-7 space-y-4">{busy&&!periods.length&&<p className="text-slate-600">Cargando períodos…</p>}{periods.map(period=><article key={period.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold">{period.name}</h2><span className={`rounded-full px-3 py-1 text-sm font-semibold ${styles[period.status.code]}`}>{period.status.name}</span></div><p className="mt-2 text-sm text-slate-500">{period.code} · {date(period.startDate)} – {date(period.endDate)}</p></div>{next[period.status.code]&&<button disabled={busy} onClick={()=>advance(period)} className="self-start rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold text-slate-700 hover:border-emerald-600 hover:text-emerald-700 disabled:opacity-50">{actions[period.status.code]}</button>}</div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-sky-50 p-4"><p className="text-sm text-sky-700">Autoevaluaciones</p><p className="mt-1 text-2xl font-bold">{period.summary.submitted} / {period.summary.eligibleRoles}</p><p className="text-sm text-sky-700">{period.summary.pendingSubmission} pendiente(s)</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-sm text-amber-700">Calibraciones</p><p className="mt-1 text-2xl font-bold">{period.summary.calibrated} / {period._count.roleMaturities}</p><p className="text-sm text-amber-700">{period.summary.pendingCalibration} pendiente(s)</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-600">Avance de autoevaluación</p><p className="mt-1 text-2xl font-bold">{period.summary.eligibleRoles?Math.round(period.summary.submitted/period.summary.eligibleRoles*100):0}%</p><div className="mt-2 h-2 rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-500" style={{width:`${period.summary.eligibleRoles?Math.min(period.summary.submitted/period.summary.eligibleRoles*100,100):0}%`}}/></div></div></div><dl className="mt-5 grid gap-4 border-t border-slate-200 pt-5 sm:grid-cols-4"><div><dt className="text-sm text-slate-500">Autoevaluación</dt><dd className="mt-1 font-semibold">{datetime(period.selfAssessmentOpensAt)} – {datetime(period.selfAssessmentClosesAt)}</dd></div><div><dt className="text-sm text-slate-500">Cierre de calibración</dt><dd className="mt-1 font-semibold">{datetime(period.calibrationClosesAt)}</dd></div><div><dt className="text-sm text-slate-500">Versión</dt><dd className="mt-1 font-semibold">{period.configurationVersion}</dd></div><div><dt className="text-sm text-slate-500">Actividad</dt><dd className="mt-1 font-semibold">{period._count.selfAssessments} autoevaluación(es) · {period._count.roleMaturities} resultado(s)</dd></div></dl></article>)}</div>
   {periods.filter(period=>period.status.code==="AUTOEVALUACION").map(period=><section key={`communications-${period.id}`} className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="font-bold">Comunicaciones de {period.name}</h2><p className="mt-1 text-sm text-slate-600">Solo incluye roles activos que tienen comportamientos observables configurados. Los recordatorios masivos de cursos se administran fuera de Mochelab.</p><div className="mt-4 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>communicate(period,"OPENING")} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Comunicar apertura</button><button disabled={busy||period.summary.pendingSubmission===0} onClick={()=>communicate(period,"REMINDER")} className="rounded-xl border border-amber-400 bg-white px-4 py-2.5 text-sm font-bold text-amber-800 disabled:opacity-50">Recordar pendientes ({period.summary.pendingSubmission})</button></div></section>)}
   <div className="mt-7 flex gap-5 text-sm font-semibold"><a href="/madurez/configuracion" className="text-emerald-700">Configurar formulario</a><a href="/madurez/calibraciones" className="text-slate-600">Ver calibraciones</a></div>
  </div>
 </main>
}
