import { useCallback, useEffect, useState } from "react";
import { apiUrl, demoHeaders } from "../directory/DirectoryShell";

type Role={id:string;name:string}; type Behavior={id:string;statement:string;weight:number;active:boolean;roles:{role:Role}[]}; type Dimension={id:string;code:string;name:string;weight:number;active:boolean;behaviors:Behavior[]};
export function MaturityConfigurationPage(){
 const [dimensions,setDimensions]=useState<Dimension[]>([]),[roles,setRoles]=useState<Role[]>([]),[message,setMessage]=useState("");
 const [dimension,setDimension]=useState({code:"",name:"",description:"",weight:1});
 const [behavior,setBehavior]=useState({dimensionId:"",code:"",statement:"",weight:1,roleIds:[] as string[]});
 const load=useCallback(async()=>{const [a,b]=await Promise.all([fetch(`${apiUrl}/api/maturity/admin/configuration`,{headers:demoHeaders}),fetch(`${apiUrl}/api/academy/roles`,{headers:demoHeaders})]);if(!a.ok||!b.ok){setMessage("No se pudo cargar la configuración");return;}const data=await a.json() as Dimension[];setDimensions(data);setRoles(await b.json());setBehavior(x=>({...x,dimensionId:x.dimensionId||data[0]?.id||""}));},[]); useEffect(()=>{void load()},[load]);
 async function send(path:string,method:"POST"|"PATCH",body:unknown){const r=await fetch(`${apiUrl}/api/maturity/admin/configuration/${path}`,{method,headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok){setMessage(data.message??"No se pudo guardar");return false;}setMessage("Configuración guardada correctamente.");await load();return true;}
 async function addDimension(){if(await send("dimensions","POST",dimension))setDimension({code:"",name:"",description:"",weight:1})} async function addBehavior(){if(await send("behaviors","POST",behavior))setBehavior(x=>({...x,code:"",statement:"",weight:1,roleIds:[]}))} function role(id:string){setBehavior(x=>({...x,roleIds:x.roleIds.includes(id)?x.roleIds.filter(y=>y!==id):[...x.roleIds,id]}))}
 const input="rounded-xl border border-slate-300 px-4 py-3 text-base";
 return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl justify-between px-5 py-4"><a href="/" className="font-bold">Mochelab <span className="text-emerald-600">2.0</span></a><b>Administrador</b></div></header><div className="mx-auto max-w-6xl px-5 py-8"><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">Configuración de madurez</p><h1 className="mt-2 text-3xl font-bold">Dimensiones y comportamientos</h1><p className="mt-3 text-slate-600">Los períodos iniciados conservarán su configuración original.</p>{message&&<p className={`mt-5 rounded-xl p-4 font-semibold ${message.includes("correctamente")?"bg-emerald-100 text-emerald-800":"bg-rose-100 text-rose-800"}`}>{message}</p>}
 <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Nueva dimensión</h2><div className="mt-4 grid gap-3"><input aria-label="Código" className={input} placeholder="Código" value={dimension.code} onChange={e=>setDimension({...dimension,code:e.target.value})}/><input aria-label="Nombre" className={input} placeholder="Nombre" value={dimension.name} onChange={e=>setDimension({...dimension,name:e.target.value})}/><textarea aria-label="Descripción" className={input} placeholder="Descripción" value={dimension.description} onChange={e=>setDimension({...dimension,description:e.target.value})}/><input aria-label="Peso" className={input} type="number" min=".01" step=".01" value={dimension.weight} onChange={e=>setDimension({...dimension,weight:Number(e.target.value)})}/><button disabled={!dimension.code||!dimension.name} onClick={()=>void addDimension()} className="rounded-xl bg-emerald-600 p-3 font-bold text-white disabled:bg-slate-300">Crear dimensión</button></div></section>
 <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Nuevo comportamiento</h2><div className="mt-4 grid gap-3"><select aria-label="Dimensión" className={input} value={behavior.dimensionId} onChange={e=>setBehavior({...behavior,dimensionId:e.target.value})}><option value="">Dimensión</option>{dimensions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input aria-label="Código" className={input} placeholder="Código" value={behavior.code} onChange={e=>setBehavior({...behavior,code:e.target.value})}/><textarea aria-label="Comportamiento" className={input} placeholder="Comportamiento observable" value={behavior.statement} onChange={e=>setBehavior({...behavior,statement:e.target.value})}/><div className="flex flex-wrap gap-2">{roles.map(x=><button type="button" key={x.id} onClick={()=>role(x.id)} className={`rounded-full border px-3 py-2 text-sm ${behavior.roleIds.includes(x.id)?"border-emerald-600 bg-emerald-50":"border-slate-300"}`}>{x.name}</button>)}</div><button disabled={!behavior.dimensionId||!behavior.code||!behavior.statement||!behavior.roleIds.length} onClick={()=>void addBehavior()} className="rounded-xl bg-emerald-600 p-3 font-bold text-white disabled:bg-slate-300">Crear comportamiento</button></div></section></div>
 <div className="mt-8 space-y-4">{dimensions.map(d=><section key={d.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="text-lg font-bold">{d.name}</h2><p className="text-sm text-slate-500">{d.code} · Peso {Number(d.weight)}</p></div><button onClick={()=>void send(`dimensions/${d.id}`,"PATCH",{active:!d.active})} className="font-bold text-emerald-700">{d.active?"Activa":"Inactiva"}</button></div><div className="mt-4 space-y-3 border-t pt-4">{d.behaviors.map(b=><article key={b.id} className="flex justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><b>{b.statement}</b><p className="mt-2 text-sm text-slate-500">{b.roles.map(x=>x.role.name).join(", ")} · Peso {Number(b.weight)}</p></div><button onClick={()=>void send(`behaviors/${b.id}`,"PATCH",{active:!b.active})} className="font-bold text-emerald-700">{b.active?"Activo":"Inactivo"}</button></article>)}{!d.behaviors.length&&<p className="text-sm text-slate-500">Sin comportamientos.</p>}</div></section>)}</div></div></main>;
}
