import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { AlertTriangle, CheckCircle2, SlidersHorizontal, Target, Trophy, UserRound, UsersRound, X } from "lucide-react";
import { apiUrl, demoHeaders } from "../directory/DirectoryShell";
import { MultiSelect } from "../components/MultiSelect";
import { downloadCsv } from "../utils/csv";
import { defaultRoleFilterIds } from "../utils/defaultRoleFilters";
import { compareRoleThenPerson } from "../utils/ordering";

type Option={id:string;label:string;status?:string};
type TeamRow={id:string;teamId:string;team:string;program:string;period:string;periodId:string;score:number;level:string;evaluatedAt:string;comments:string|null};
type RoleRow={id:string;person:string;roleId:string;role:string;teamId:string;team:string;period:string;periodId:string;score:number;selfAssessmentScore:number|null;calibratedScore:number|null;level:string;evaluatedAt:string};
type Assignment={id:string;person:{names:string;dni:string};role:{id:string;name:string};team:{id:string;sourceId:string;program:{name:string}};status:{code:string;name:string}};
type AcademyRole={id:string;name:string;type:string};
type TargetRow={indicator:{name:string};target:number;validFrom:string;validUntil:string|null;status:{code:string;name:string}};
type Tab="summary"|"teams"|"roles"|"history";
const levels=["4. MAESTRO","3. OFICIAL","2. PRINCIPIANTE","1. POSTULANTE","SIN EVALUACIÓN"] as const;
const norm=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();
const levelKey=(value?:string)=>{const text=norm(value??"");return levels.find(level=>text.includes(level.split(". ").at(-1)!))??"SIN EVALUACIÓN"};
const scoreOf=(row:RoleRow)=>row.calibratedScore??row.selfAssessmentScore??row.score;

function CompactMaturityFilters({open,setOpen,search,setSearch,periodIds,setPeriodIds,teamIds,setTeamIds,roleIds,setRoleIds,roleOptions,options}:{open:boolean;setOpen:(value:boolean)=>void;search:string;setSearch:(value:string)=>void;periodIds:string[];setPeriodIds:(value:string[])=>void;teamIds:string[];setTeamIds:(value:string[])=>void;roleIds:string[];setRoleIds:(value:string[])=>void;roleOptions:Option[];options:{teams:Option[];periods:Option[]}}){const label=(items:Option[],id:string)=>items.find(item=>item.id===id)?.label??id;const count=(search?1:0)+periodIds.length+teamIds.length+roleIds.length;const clear=()=>{setSearch("");setPeriodIds([]);setTeamIds([]);setRoleIds([])};return <div className="mt-5"><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={()=>setOpen(!open)} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold"><SlidersHorizontal size={16}/>Filtros{count>0&&<span className="rounded-full bg-red-50 px-2 py-0.5 text-xs text-red-700">{count}</span>}</button>{count>0&&<><div className="flex flex-wrap gap-2">{search&&<MaturityChip label={`Búsqueda: ${search}`} clear={()=>setSearch("")}/>} {periodIds.map(id=><MaturityChip key={id} label={label(options.periods,id)} clear={()=>setPeriodIds(periodIds.filter(value=>value!==id))}/>)}{teamIds.map(id=><MaturityChip key={id} label={label(options.teams,id)} clear={()=>setTeamIds(teamIds.filter(value=>value!==id))}/>)}{roleIds.map(id=><MaturityChip key={id} label={label(roleOptions,id)} clear={()=>setRoleIds(roleIds.filter(value=>value!==id))}/>)}</div><button type="button" onClick={clear} className="text-sm font-bold text-red-700">Limpiar</button></>}</div>{open&&<div className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-2 xl:grid-cols-4"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar persona, equipo o rol" className="control"/><MultiSelect label="Períodos" emptyLabel="Todos los períodos" value={periodIds} onChange={setPeriodIds} options={options.periods}/><MultiSelect label="Equipos" emptyLabel="Todos los equipos" value={teamIds} onChange={setTeamIds} options={options.teams}/><MultiSelect label="Roles" emptyLabel="Todos los roles" value={roleIds} onChange={setRoleIds} options={roleOptions}/></div>}</div>}
function MaturityChip({label,clear}:{label:string;clear:()=>void}){return <span className="inline-flex max-w-[15rem] items-center gap-1 rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700"><span className="truncate">{label}</span><button type="button" onClick={clear} aria-label={`Quitar ${label}`} className="text-slate-500"><X size={13}/></button></span>}

export function TeamMaturityPage(){
 const query=new URLSearchParams(location.search),split=(key:string)=>query.get(key)?.split(",").filter(Boolean)??[];
 const roleDefaultsInitialized=useRef(query.has("roles"));
 const[options,setOptions]=useState<{teams:Option[];periods:Option[]}>({teams:[],periods:[]});
 const[teams,setTeams]=useState<TeamRow[]>([]),[roles,setRoles]=useState<RoleRow[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[academyRoles,setAcademyRoles]=useState<AcademyRole[]>([]),[targets,setTargets]=useState<TargetRow[]>([]);
 const[periodIds,setPeriodIds]=useState<string[]>(split("periods")),[teamIds,setTeamIds]=useState<string[]>(split("teams")),[roleIds,setRoleIds]=useState<string[]>(split("roles")),[search,setSearch]=useState(query.get("q")??""),[tab,setTab]=useState<Tab>((query.get("tab") as Tab)||"summary"),[filtersOpen,setFiltersOpen]=useState(Boolean(query.get("q")||query.get("periods")||query.get("teams")||query.get("roles")));
 const[message,setMessage]=useState(""),[showForm,setShowForm]=useState(false),[teamId,setTeamId]=useState(""),[score,setScore]=useState(""),[comments,setComments]=useState("");

 async function load(){
  const[h,o,r,t]=await Promise.all([
   fetch(`${apiUrl}/api/maturity/admin/history`,{headers:demoHeaders}),
   fetch(`${apiUrl}/api/maturity/admin/team-maturities/options`,{headers:demoHeaders}),
   fetch(`${apiUrl}/api/academy/roles`,{headers:demoHeaders}),
   fetch(`${apiUrl}/api/targets`,{headers:demoHeaders}),
  ]);
  if(!h.ok||!o.ok){setMessage("No se pudo cargar la vista de madurez.");return}
  const history=await h.json() as {teams:TeamRow[];roles:RoleRow[]};
  const nextOptions=await o.json() as {teams:Option[];periods:Option[]};
  setTeams(history.teams);setRoles(history.roles);setOptions(nextOptions);
  if(r.ok)setAcademyRoles(await r.json());
  if(t.ok)setTargets(await t.json());
  setPeriodIds(current=>current.length?current:(nextOptions.periods[0]?[nextOptions.periods[0].id]:[]));
 }
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const controller=new AbortController(),q=new URLSearchParams({statusCodes:"ACTIVO"});if(teamIds.length)q.set("teamIds",teamIds.join(","));if(roleIds.length)q.set("roleIds",roleIds.join(","));const timer=setTimeout(()=>{fetch(`${apiUrl}/api/person-role-assignments?${q}`,{headers:demoHeaders,signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("No se pudieron cargar las asignaciones de madurez");return response.json() as Promise<Assignment[]>}).then(setAssignments).catch((reason:Error)=>{if(reason.name!=="AbortError")setMessage(reason.message)})},250);return()=>{clearTimeout(timer);controller.abort()}},[teamIds,roleIds]);
 useEffect(()=>{const next=new URLSearchParams();if(search)next.set("q",search);if(periodIds.length)next.set("periods",periodIds.join(","));if(teamIds.length)next.set("teams",teamIds.join(","));if(roleIds.length)next.set("roles",roleIds.join(","));if(tab!=="summary")next.set("tab",tab);history.replaceState(null,"",`${location.pathname}${next.size?`?${next}`:""}`)},[search,periodIds,teamIds,roleIds,tab]);

 const selectedPeriods=periodIds.length?periodIds:options.periods.map(item=>item.id);
 const roleOptions=useMemo(()=>academyRoles.map(item=>({id:item.id,label:item.name})).sort((a,b)=>a.label.localeCompare(b.label,"es")),[academyRoles]);
 useEffect(()=>{if(roleDefaultsInitialized.current||roleOptions.length===0)return;roleDefaultsInitialized.current=true;setRoleIds(defaultRoleFilterIds(roleOptions,item=>item.id,item=>item.label))},[roleOptions]);
 const filteredTeams=useMemo(()=>teams.filter(item=>selectedPeriods.includes(item.periodId)&&(teamIds.length===0||teamIds.includes(item.teamId))&&(!search||norm(`${item.team} ${item.program}`).includes(norm(search)))),[teams,selectedPeriods,teamIds,search]);
 const filteredRoles=useMemo(()=>roles.filter(item=>selectedPeriods.includes(item.periodId)&&(teamIds.length===0||teamIds.includes(item.teamId))&&(roleIds.length===0||roleIds.includes(item.roleId))&&(!search||norm(`${item.person} ${item.role} ${item.team}`).includes(norm(search)))).sort(compareRoleThenPerson(item=>item.role,item=>item.person)),[roles,selectedPeriods,teamIds,roleIds,search]);
 const visibleAssignments=useMemo(()=>assignments.filter(item=>(teamIds.length===0||teamIds.includes(item.team.id))&&(roleIds.length===0||roleIds.includes(item.role.id))&&(!search||norm(`${item.person.names} ${item.person.dni} ${item.role.name} ${item.team.sourceId} ${item.team.program.name}`).includes(norm(search)))).sort(compareRoleThenPerson(item=>item.role.name,item=>item.person.names)),[assignments,teamIds,roleIds,search]);
 const visibleTeamOptions=useMemo(()=>options.teams.filter(item=>teamIds.length===0||teamIds.includes(item.id)).filter(item=>!search||norm(item.label).includes(norm(search))),[options.teams,teamIds,search]);
 const currentPeriod=options.periods.find(item=>item.id===periodIds[0]);
 const currentRoleRows=filteredRoles.filter(item=>item.periodId===periodIds[0]);
 const currentTeamRows=filteredTeams.filter(item=>item.periodId===periodIds[0]);
 const coverage=visibleAssignments.length?Math.round(currentRoleRows.length/visibleAssignments.length*100):0;
 const roleAverage=currentRoleRows.length?currentRoleRows.reduce((sum,item)=>sum+scoreOf(item),0)/currentRoleRows.length:0;
 const teamAverage=currentTeamRows.length?currentTeamRows.reduce((sum,item)=>sum+item.score,0)/currentTeamRows.length:0;
 const pendingRoles=Math.max(0,visibleAssignments.length-currentRoleRows.length);
 const pendingTeams=Math.max(0,visibleTeamOptions.length-currentTeamRows.length);
 const roleTypes=useMemo(()=>new Map(academyRoles.map(item=>[item.name,item.type||"Sin tipo"])),[academyRoles]);
 const roleMatrix=useMemo(()=>{
  const map=new Map<string,Record<string,number>>();
  visibleAssignments.forEach(item=>{const key=`${roleTypes.get(item.role.name)??"Sin tipo"}|${item.role.name}`;if(!map.has(key))map.set(key,Object.fromEntries(levels.map(level=>[level,0])));const evaluation=currentRoleRows.find(row=>row.person===item.person.names&&row.role===item.role.name&&row.teamId===item.team.id);map.get(key)![levelKey(evaluation?.level)]++});
  return [...map].map(([key,counts])=>{const[type,role]=key.split("|");return{type,role,counts,total:Object.values(counts).reduce((a,b)=>a+b,0)}}).sort((a,b)=>a.type.localeCompare(b.type)||a.role.localeCompare(b.role));
 },[visibleAssignments,currentRoleRows,roleTypes]);
 const distribution=levels.slice(0,4).map(level=>{const count=currentRoleRows.filter(row=>levelKey(row.level)===level).length;const target=targets.find(item=>norm(item.indicator.name).includes(norm(level.split(". ").at(-1)!)))?.target??null;return{level,count,percent:currentRoleRows.length?count/currentRoleRows.length*100:0,target}});
 const trends=useMemo(()=>options.periods.map(period=>{const rr=roles.filter(item=>item.periodId===period.id&&(teamIds.length===0||teamIds.includes(item.teamId))&&(roleIds.length===0||roleIds.includes(item.roleId))),tt=teams.filter(item=>item.periodId===period.id&&(teamIds.length===0||teamIds.includes(item.teamId)));return{label:period.label,roles:rr.length?rr.reduce((s,x)=>s+scoreOf(x),0)/rr.length:null,teams:tt.length?tt.reduce((s,x)=>s+x.score,0)/tt.length:null}}).filter(item=>item.roles!==null||item.teams!==null).slice(-6),[options.periods,roles,teams,teamIds,roleIds]);
 const priorities=[...visibleTeamOptions.filter(option=>!currentTeamRows.some(row=>row.teamId===option.id)).map(option=>({entity:option.label,type:"Equipo",detail:"Sin evaluación"})),...visibleAssignments.filter(item=>!currentRoleRows.some(row=>row.person===item.person.names&&row.role===item.role.name&&row.teamId===item.team.id)).map(item=>({entity:item.person.names,type:"Persona / Rol",detail:item.role.name}))];

 async function save(){if(!teamId||!periodIds[0]||score==="")return;const response=await fetch(`${apiUrl}/api/maturity/admin/team-maturities`,{method:"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify({teamId,periodId:periodIds[0],score:Number(score),comments})});const body=await response.json().catch(()=>({}));if(!response.ok){setMessage(body.message??"No se pudo guardar la madurez.");return}setMessage("Madurez del equipo registrada.");setShowForm(false);setTeamId("");setScore("");setComments("");await load()}
 function exportRows(){downloadCsv("madurez.csv",["Tipo","Entidad","Rol/Programa","Periodo","Puntaje","Nivel"],[...filteredTeams.map(x=>["Equipo",x.team,x.program,x.period,x.score,x.level]),...filteredRoles.map(x=>["Persona / Rol",x.person,`${x.role} · ${x.team}`,x.period,scoreOf(x),x.level])])}

 return <main className="min-h-screen bg-[#f6f7f9] text-slate-800"><div className="mx-auto max-w-[1480px] px-5 py-7">
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
   <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold">Vista ejecutiva de madurez</p><p className="mt-1 text-xs text-slate-400">Cobertura, evolución, brechas y registros históricos en una sola vista.</p></div><div className="flex gap-2"><button onClick={exportRows} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Exportar</button><button onClick={()=>setShowForm(value=>!value)} className="brand-action rounded-xl px-4 py-2 text-sm font-semibold">Consolidar madurez de equipo</button></div></div>
   <CompactMaturityFilters open={filtersOpen} setOpen={setFiltersOpen} search={search} setSearch={setSearch} periodIds={periodIds} setPeriodIds={setPeriodIds} teamIds={teamIds} setTeamIds={setTeamIds} roleIds={roleIds} setRoleIds={setRoleIds} roleOptions={roleOptions} options={options}/>
   {showForm&&<div className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-2 2xl:grid-cols-[minmax(0,1fr)_180px_minmax(0,1fr)_auto]"><select value={teamId} onChange={e=>setTeamId(e.target.value)} className="rounded-xl border bg-white px-3 py-2"><option value="">Selecciona equipo</option>{options.teams.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input type="number" min="0" max="2" step=".01" value={score} onChange={e=>setScore(e.target.value)} placeholder="Puntaje 0 a 2" className="rounded-xl border px-3 py-2"/><input value={comments} onChange={e=>setComments(e.target.value)} placeholder="Comentarios" className="rounded-xl border px-3 py-2"/><button disabled={!teamId||!periodIds[0]||score===""} onClick={()=>void save()} className="rounded-xl bg-cyan-400 px-4 py-2 font-bold disabled:opacity-40">Guardar</button></div>}
  </section>
  {message&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-semibold">{message}</p>}
  <nav className="mt-5 flex gap-1 border-b border-slate-200">{([["summary","Resumen"],["teams","Equipos"],["roles","Personas y roles"],["history","Historial"]] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab===id?"border-slate-900 text-slate-900":"border-transparent text-slate-400"}`}>{label}</button>)}</nav>

  {tab==="summary"&&<div className="mt-6 space-y-5">
   <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={<CheckCircle2/>} label="Cobertura de evaluación" value={`${coverage}%`} detail={`${currentRoleRows.length} de ${visibleAssignments.length} asignaciones evaluadas`}/><Kpi icon={<UserRound/>} label="Índice promedio de roles" value={roleAverage.toFixed(2)} detail={`${currentRoleRows.length} evaluaciones del período`}/><Kpi icon={<UsersRound/>} label="Índice promedio de equipos" value={teamAverage.toFixed(2)} detail={`${currentTeamRows.length} equipos evaluados`}/><Kpi icon={<AlertTriangle/>} label="Pendientes de evaluación" value={pendingRoles+pendingTeams} detail={`${pendingRoles} roles · ${pendingTeams} equipos`} alert/></section>
   <Card title="Nivel de madurez: número de roles" subtitle="Universo de asignaciones activas según los filtros seleccionados." extra={currentPeriod?.label}><table className="w-full min-w-[850px] text-left text-sm"><thead><tr><th className="p-4">Tipo</th><th>Rol</th>{levels.map(x=><th key={x} className="text-center">{x}</th>)}<th className="text-center">Total</th></tr></thead><tbody>{roleMatrix.map(row=><tr key={`${row.type}-${row.role}`} className="border-t"><td className="p-4 text-slate-500">{row.type}</td><td className="font-semibold">{row.role}</td>{levels.map(level=><td key={level} className="text-center"><Count value={row.counts[level]}/></td>)}<td className="text-center font-bold">{row.total}</td></tr>)}</tbody></table></Card>
   <section className="grid gap-5 2xl:grid-cols-[minmax(0,1.4fr)_minmax(0,.8fr)]"><Trend data={trends}/><Distribution data={distribution} coverage={coverage}/></section>
   <Card title="Prioridades de atención" subtitle="Sin evaluación, retrocesos, estancamientos y niveles iniciales." extra={`${priorities.length} alertas`}><table className="w-full text-left text-sm"><thead><tr><th className="p-4">Entidad</th><th>Tipo</th><th>Resultado actual</th><th>Motivo</th></tr></thead><tbody>{priorities.slice(0,20).map((item,index)=><tr key={index} className="border-t"><td className="p-4 font-semibold">{item.entity}<small className="block text-slate-400">{item.detail}</small></td><td>{item.type}</td><td>Sin evaluación</td><td><span className="ds-badge ds-badge-danger">Sin evaluación</span></td></tr>)}</tbody></table></Card>
  </div>}
  {tab==="teams"&&<Card title="Madurez actual por equipo" subtitle="Situación del período seleccionado."><DataTable headers={["Equipo","Programa","Índice","Nivel","Estado"]} rows={visibleTeamOptions.map(option=>{const row=currentTeamRows.find(item=>item.teamId===option.id);return[option.label,row?.program??"—",row?.score.toFixed(2)??"—",row?.level??"—",<Status ok={Boolean(row)}/>]})}/></Card>}
  {tab==="roles"&&<Card title="Madurez actual por persona y rol" subtitle="Asignaciones y resultado del período seleccionado."><DataTable headers={["Trabajador","Rol","Equipo","Índice","Nivel","Estado"]} rows={visibleAssignments.map(item=>{const row=currentRoleRows.find(x=>x.person===item.person.names&&x.role===item.role.name&&x.teamId===item.team.id);return[<span><b>{item.person.names}</b><small className="block text-slate-400">DNI: {item.person.dni}</small></span>,item.role.name,`${item.team.sourceId} · ${item.team.program.name}`,row?scoreOf(row).toFixed(2):"—",row?.level??"—",<Status ok={Boolean(row)}/>]})}/></Card>}
  {tab==="history"&&<Card title="Historial de madurez" subtitle="Resultados registrados en todos los períodos seleccionados."><DataTable headers={["Tipo","Entidad","Rol / Programa","Período","Índice","Nivel","Fecha"]} rows={[...filteredRoles.map(x=>["Persona / Rol",x.person,`${x.role} · ${x.team}`,x.period,scoreOf(x).toFixed(2),x.level,x.evaluatedAt]),...filteredTeams.map(x=>["Equipo",x.team,x.program,x.period,x.score.toFixed(2),x.level,x.evaluatedAt])]}/></Card>}
 </div></main>
}

function Card({title,subtitle,extra,children}:{title:string;subtitle:string;extra?:string;children:ReactNode}){return <section className="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-start justify-between gap-4 border-b px-5 py-4"><div><h2 className="text-base font-bold">{title}</h2><p className="mt-1 text-xs text-slate-400">{subtitle}</p></div>{extra&&<span className="rounded-full bg-slate-50 px-3 py-1 text-xs text-slate-500">{extra}</span>}</div>{children}</section>}
function Kpi({icon,label,value,detail,alert=false}:{icon:ReactNode;label:string;value:string|number;detail:string;alert?:boolean}){return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3 text-sm font-semibold text-slate-400"><span className={`grid h-9 w-9 place-items-center rounded-xl [&>svg]:h-5 [&>svg]:w-5 ${alert?"bg-rose-50 text-rose-600":"bg-cyan-50 text-cyan-600"}`}>{icon}</span>{label}</div><strong className={`mt-4 block text-3xl ${alert?"text-red-600":"text-slate-800"}`}>{value}</strong><small className="mt-2 block text-slate-400">{detail}</small></article>}
function Count({value}:{value:number}){return value?<span className="inline-flex min-w-9 justify-center rounded-lg bg-cyan-50 px-2 py-1 font-bold text-cyan-700">{value}</span>:<span className="text-slate-300">0</span>}
function Status({ok}:{ok:boolean}){return <span className={`ds-badge ${ok?"ds-badge-success":"ds-badge-danger"}`}>{ok?"EVALUADO":"PENDIENTE"}</span>}
function DataTable({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{headers.map((h,i)=><th key={h} className={i===0?"p-4":""}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-t">{row.map((cell,j)=><td key={j} className={j===0?"p-4":"py-4 pr-4"}>{cell}</td>)}</tr>)}</tbody></table>}
function Trend({data}:{data:{label:string;roles:number|null;teams:number|null}[]}){const width=680,height=240,pad=45,points=(key:"roles"|"teams")=>data.map((item,i)=>`${pad+i*((width-pad*2)/Math.max(1,data.length-1))},${height-pad-((item[key]??0)/2.2)*(height-pad*2)}`).join(" ");return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-bold">Evolución de madurez</h2><p className="mt-1 text-xs text-slate-400">Últimos períodos con información</p><svg viewBox={`0 0 ${width} ${height}`} className="mt-4 w-full"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} stroke="#e5e7eb"/><polyline points={points("teams")} fill="none" stroke="#d71920" strokeWidth="4"/><polyline points={points("roles")} fill="none" stroke="#08aeca" strokeWidth="4" strokeDasharray="8 6"/>{data.map((item,i)=><text key={item.label} x={pad+i*((width-pad*2)/Math.max(1,data.length-1))} y={height-12} textAnchor="middle" fontSize="11" fill="#94a3b8">{item.label}</text>)}</svg></section>}
function Distribution({data,coverage}:{data:{level:string;count:number;percent:number;target:number|null}[];coverage:number}){const colors=["#d7dde3","#08aeca","#f3a700","#ff6267"];return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-bold">Madurez global de roles</h2><p className="mt-1 text-xs text-slate-400">Porcentaje sobre roles evaluados</p><div className="mt-6 space-y-5">{data.map((item,i)=><div key={item.level}><div className="flex justify-between text-sm"><span>{item.level}</span><b>{item.percent.toFixed(2)}%</b></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{width:`${item.percent}%`,background:colors[i]}}/></div><small className="text-slate-400">{item.count} roles</small></div>)}</div><p className="mt-6 rounded-xl bg-slate-50 p-3 text-xs"><b>Cobertura:</b> {coverage}%</p><div className="mt-5 border-t pt-5"><p className="flex items-center gap-2 text-sm font-bold"><Target size={17} className="text-red-600"/>Objetivo de distribución</p><div className="mt-4 space-y-2">{data.map(item=>{const variance=item.target===null?null:item.percent-item.target;return <div key={item.level} className="grid grid-cols-[1fr_auto_auto] gap-4 text-xs"><span>{item.level}</span><span>Meta {item.target===null?"—":`${item.target.toFixed(2)}%`}</span><b className={variance===null?"text-slate-400":variance>=0?"text-emerald-600":"text-red-600"}>{variance===null?"—":`${variance>=0?"+":""}${variance.toFixed(2)} pp`}</b></div>})}</div></div></section>}
