import{useCallback,useEffect,useState}from"react";
import{apiUrl,demoHeaders}from"../directory/DirectoryShell";
import{EmptyState,ErrorState,LoadingState}from"../components/AsyncState";
type Row={id:string;eventType:string;recipient:string|null;subject:string;status:string;source:string;createdAt:string;personRole?:{person:{names:string};role:{name:string};team:{sourceId:string}}|null};type Response={items:Row[];total:number;page:number;pageSize:number;pages:number};
const labels:Record<string,string>={ROLE_ASSIGNED:"Rol asignado",ROLE_REACTIVATED:"Rol reactivado",ROLE_CLOSED:"Rol cerrado",SELF_ASSESSMENT_OPENED:"Apertura de autoevaluación",SELF_ASSESSMENT_REMINDER:"Recordatorio de autoevaluación",MATURITY_RESULT_AVAILABLE:"Resultado de madurez calibrado"};
const statusLabels:Record<string,string>={PENDIENTE:"Pendiente",ENVIADA:"Enviada",FALLIDA:"Fallida",OMITIDA_SIN_CORREO:"Omitida: sin correo"};
export function CommunicationsPage(){const[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0);const pageSize=25;
 const load=useCallback(()=>{setLoading(true);setError("");const query=new URLSearchParams({page:String(page),pageSize:String(pageSize)});if(status)query.set("status",status);fetch(`${apiUrl}/api/communications?${query}`,{headers:demoHeaders}).then(async response=>{if(!response.ok)throw new Error("No se pudieron cargar las comunicaciones");return response.json() as Promise<Response>}).then(data=>{setRows(data.items);setPages(data.pages);setTotal(data.total)}).catch(reason=>setError(reason instanceof Error?reason.message:"Error inesperado")).finally(()=>setLoading(false))},[page,status]);useEffect(()=>{load()},[load]);useEffect(()=>setPage(1),[status]);
 return <main className="ds-page"><div className="ds-page-content"><p className="ds-eyebrow">Administración</p><h1 className="ds-page-title">Comunicaciones</h1><p className="ds-page-description">Consulta los envíos generados, su destinatario y el estado de entrega.</p><div className="mt-6 flex flex-wrap items-end justify-between gap-3"><label className="w-full max-w-sm text-sm font-bold">Estado<select value={status} onChange={event=>setStatus(event.target.value)} className="ds-control mt-2"><option value="">Todos los estados</option><option value="PENDIENTE">Pendiente</option><option value="ENVIADA">Enviada</option><option value="FALLIDA">Fallida</option><option value="OMITIDA_SIN_CORREO">Omitida: sin correo</option></select></label><a href="/configuracion/comunicaciones" className="ds-button ds-button-secondary">Editar plantillas</a></div><div className="mt-5">{loading?<LoadingState label="Cargando comunicaciones…"/>:error?<ErrorState message={error} onRetry={load}/>:!rows.length?<EmptyState detail="No existen comunicaciones para el estado seleccionado."/>:<section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[800px] text-left"><thead><tr><th className="p-4">Fecha</th><th>Evento</th><th>Persona / rol</th><th>Destinatario</th><th>Estado</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="p-4">{new Date(row.createdAt).toLocaleString("es-PE")}</td><td><b>{labels[row.eventType]??row.eventType}</b><small className="block text-slate-500">{row.subject}</small></td><td>{row.personRole?`${row.personRole.person.names} · ${row.personRole.role.name} · ${row.personRole.team.sourceId}`:"—"}</td><td>{row.recipient??"Sin correo"}</td><td><span className="rounded-full bg-slate-100 px-3 py-1 font-bold">{statusLabels[row.status]??row.status}</span></td></tr>)}</tbody></table></section>}</div>{!loading&&!error&&total>0&&<div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">{total} comunicación(es)</p><div className="flex items-center gap-3"><button disabled={page===1} onClick={()=>setPage(value=>value-1)} className="ds-button ds-button-secondary disabled:opacity-40">Anterior</button><span className="text-sm font-bold">Página {page} de {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)} className="ds-button ds-button-secondary disabled:opacity-40">Siguiente</button></div></div>}</div></main>}
