import { useCallback, useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "../components/AsyncState";
import { apiUrl, demoHeaders } from "../directory/DirectoryShell";

type Row={id:string;eventType:string;recipient:string|null;subject:string;status:string;createdAt:string;errorSummary?:string|null;personRole?:{person:{names:string};role:{name:string};team:{sourceId:string}}|null};
type Response={items:Row[];total:number;page:number;pageSize:number;pages:number};
type Provider={provider:string;enabled:boolean;configured:boolean;missing:string[];senderName:string;transport:string;mode:"ENVIO"|"SOLO_COLA";automatic?:{enabled:boolean;schedule:string;timeZone:string;nextRunAt:string|null;lastRunAt:string|null}};
const labels:Record<string,string>={ROLE_ASSIGNED:"Rol asignado",ROLE_REACTIVATED:"Rol reactivado",ROLE_CLOSED:"Rol cerrado",SELF_ASSESSMENT_OPENED:"Apertura de autoevaluación",SELF_ASSESSMENT_REMINDER:"Recordatorio de autoevaluación",MATURITY_RESULT_AVAILABLE:"Resultado de madurez calibrado"};
const statusLabels:Record<string,string>={PENDIENTE:"Pendiente",REINTENTO:"Reintento programado",EN_PROCESO:"En proceso",ENVIADA:"Enviada",FALLIDA:"Fallida",OMITIDA_SIN_CORREO:"Omitida: sin correo"};

export function CommunicationsPage(){
  const[rows,setRows]=useState<Row[]>([]),[provider,setProvider]=useState<Provider|null>(null),[status,setStatus]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0);const pageSize=25;
  const load=useCallback(async()=>{setLoading(true);setError("");try{const query=new URLSearchParams({page:String(page),pageSize:String(pageSize)});if(status)query.set("status",status);const[r,p]=await Promise.all([fetch(`${apiUrl}/api/communications?${query}`,{headers:demoHeaders}),fetch(`${apiUrl}/api/communications/provider-status`,{headers:demoHeaders})]);if(!r.ok)throw new Error("No se pudieron cargar las comunicaciones");const data=await r.json() as Response;setRows(data.items);setPages(data.pages);setTotal(data.total);if(p.ok)setProvider(await p.json())}catch(reason){setError(reason instanceof Error?reason.message:"Error inesperado")}finally{setLoading(false)}},[page,status]);
  useEffect(()=>{void load()},[load]);useEffect(()=>setPage(1),[status]);
  async function sendPending(){setSending(true);setMessage("");const response=await fetch(`${apiUrl}/api/communications/send-pending`,{method:"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify({limit:25})});const body=await response.json().catch(()=>({}));setMessage(response.ok?`Proceso terminado: ${body.sent??0} enviado(s), ${body.failed??0} fallido(s).`:body.message??"No se pudo iniciar el envío");setSending(false);await load()}
  return <main className="ds-page"><div className="ds-page-content"><p className="ds-eyebrow">Administración</p><h1 className="ds-page-title">Comunicaciones</h1><p className="ds-page-description">Consulta los eventos registrados y controla su envío temporal mediante Google Apps Script.</p>
    {provider&&<section className={`mt-5 rounded-xl border p-4 ${provider.mode==="ENVIO"?"border-emerald-300 bg-emerald-50":"border-amber-300 bg-amber-50"}`}><b>{provider.mode==="ENVIO"?"Envío habilitado":"Modo Solo cola"}</b><p className="text-sm">{provider.mode==="ENVIO"?`Proveedor ${provider.provider} listo para enviar.`:"Los eventos se registran, pero ningún correo será enviado hasta completar la configuración."}</p>{provider.automatic&&<p className="mt-1 text-sm">Automático diario: <b>{provider.automatic.enabled?"Activo":"Inactivo"}</b> · {provider.automatic.schedule} ({provider.automatic.timeZone}){provider.automatic.nextRunAt?` · próxima ejecución ${new Date(provider.automatic.nextRunAt).toLocaleString("es-PE")}`:""}</p>}{provider.missing.length>0&&<p className="mt-1 text-sm">Pendiente: {provider.missing.join(", ")}</p>}</section>}
    {message&&<p className="mt-4 rounded-xl bg-slate-100 p-4 font-semibold">{message}</p>}
    <div className="mt-6 flex flex-wrap items-end justify-between gap-3"><label className="w-full max-w-sm text-sm font-bold">Estado<select value={status} onChange={event=>setStatus(event.target.value)} className="ds-control mt-2"><option value="">Todos los estados</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="flex gap-3"><button disabled={provider?.mode!=="ENVIO"||sending} onClick={()=>void sendPending()} className="ds-button ds-button-primary disabled:opacity-40">{sending?"Enviando…":"Enviar hasta 25 pendientes"}</button><a href="/configuracion/comunicaciones" className="ds-button ds-button-secondary">Editar plantillas</a></div></div>
    <div className="mt-5">{loading?<LoadingState label="Cargando comunicaciones…"/>:error?<ErrorState message={error} onRetry={load}/>:!rows.length?<EmptyState detail="No existen comunicaciones para el estado seleccionado."/>:<section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[800px] text-left"><thead><tr><th className="p-4">Fecha</th><th>Evento</th><th>Persona / rol</th><th>Destinatario</th><th>Estado</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="p-4">{new Date(row.createdAt).toLocaleString("es-PE")}</td><td><b>{labels[row.eventType]??row.eventType}</b><small className="block text-slate-500">{row.subject}</small></td><td>{row.personRole?`${row.personRole.person.names} · ${row.personRole.role.name} · ${row.personRole.team.sourceId}`:"—"}</td><td>{row.recipient??"Sin correo"}</td><td><span className="rounded-full bg-slate-100 px-3 py-1 font-bold">{statusLabels[row.status]??row.status}</span>{row.errorSummary&&<small className="mt-2 block max-w-xs text-red-700">{row.errorSummary}</small>}</td></tr>)}</tbody></table></section>}</div>
    {!loading&&!error&&total>0&&<div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">{total} comunicación(es)</p><div className="flex items-center gap-3"><button disabled={page===1} onClick={()=>setPage(value=>value-1)} className="ds-button ds-button-secondary disabled:opacity-40">Anterior</button><span className="text-sm font-bold">Página {page} de {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)} className="ds-button ds-button-secondary disabled:opacity-40">Siguiente</button></div></div>}
  </div></main>
}
