import { useState, type FormEvent } from "react";
import { startDemoSession, type DemoProfile } from "./demoSession";

const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:3000";
export function LoginPage(){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[waking,setWaking]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setWaking(false);setMessage("");const controller=new AbortController();const slowTimer=window.setTimeout(()=>setWaking(true),4000);const timeout=window.setTimeout(()=>controller.abort(),75000);try{const response=await fetch(`${apiUrl}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password}),signal:controller.signal});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message??"No se pudo iniciar sesión");startDemoSession(body.profile as DemoProfile,body.email,body.token);window.location.replace("/")}catch(error){setMessage(error instanceof DOMException&&error.name==="AbortError"?"El servidor no respondió en 75 segundos. Espera un momento y vuelve a intentar.":error instanceof Error?error.message:"No se pudo iniciar sesión")}finally{window.clearTimeout(slowTimer);window.clearTimeout(timeout);setBusy(false);setWaking(false)}}
 const testing=import.meta.env.VITE_APP_ENV==="development";
 return <main className="login-page"><div className="login-shell"><section className="login-brand-panel"><div className="login-brand-lockup"><span>M</span></div><div><h1>Transformación y<br/>Mejora continua</h1></div><small>Respaldo Corporativo DANPER<br/>Versión 2026.1</small></section><section className="login-form-panel"><form className="login-card" onSubmit={submit}><div><h2>Iniciar sesión</h2><p className="login-intro">Ingresa con tu cuenta de Mochelab.</p></div>{message&&<p className="login-notice" role="alert"><strong>No se pudo ingresar</strong><span>{message}</span></p>}<label className="login-field"><span>Usuario</span><input type="email" value={email} onChange={event=>setEmail(event.target.value)} required autoComplete="username" placeholder="correo@empresa.com"/></label><label className="login-field"><span>Contraseña</span><input type="password" value={password} onChange={event=>setPassword(event.target.value)} required autoComplete="current-password"/></label><button className="login-submit" type="submit" disabled={busy}>{busy?(waking&&testing?"Iniciando entorno…":"Verificando…"):"Acceder"}<span>→</span></button>{busy&&waking&&testing?<p className="login-footnote" role="status">La API gratuita de pruebas está despertando. Puede tomar cerca de un minuto.</p>:<p className="login-footnote">Si no tienes contraseña inicial, solicítala al administrador de Mochelab.</p>}</form></section></div></main>
}
