import { useState, type FormEvent } from "react";
import { startDemoSession, type DemoProfile } from "./demoSession";

const apiUrl=import.meta.env.VITE_API_URL??"http://localhost:3000";
export function LoginPage(){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const response=await fetch(`${apiUrl}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message??"No se pudo iniciar sesión");startDemoSession(body.profile as DemoProfile,body.email,body.token);window.location.replace("/")}catch(error){setMessage(error instanceof Error?error.message:"No se pudo iniciar sesión")}finally{setBusy(false)}}
 return <main className="login-page"><div className="login-shell"><section className="login-brand-panel"><div className="login-brand-lockup"><span>M</span></div><div><h1>Transformación y<br/>Mejora continua</h1></div><small>Respaldo Corporativo DANPER<br/>Versión 2026.1</small></section><section className="login-form-panel"><form className="login-card" onSubmit={submit}><div><h2>Iniciar sesión</h2><p className="login-intro">Ingresa con tu cuenta de Mochelab.</p></div>{message&&<p className="login-notice" role="alert"><strong>No se pudo ingresar</strong><span>{message}</span></p>}<label className="login-field"><span>Usuario</span><input type="email" value={email} onChange={event=>setEmail(event.target.value)} required autoComplete="username" placeholder="correo@empresa.com"/></label><label className="login-field"><span>Contraseña</span><input type="password" value={password} onChange={event=>setPassword(event.target.value)} required autoComplete="current-password"/></label><button className="login-submit" type="submit" disabled={busy}>{busy?"Verificando…":"Acceder"}<span>→</span></button><p className="login-footnote">Si no tienes contraseña inicial, solicítala al administrador de Mochelab.</p></form></section></div></main>
}
