import {useEffect,useId,useMemo,useRef,useState} from "react";
import {Check,ChevronDown,Search,X} from "lucide-react";

export type SearchableSelectOption={id:string;label:string};

export function SearchableSelect({label,options,value,onChange,placeholder="Selecciona"}:{label:string;options:SearchableSelectOption[];value:string;onChange:(value:string)=>void;placeholder?:string}){
 const[open,setOpen]=useState(false),[search,setSearch]=useState("");
 const root=useRef<HTMLDivElement>(null),listId=useId(),selected=options.find(option=>option.id===value);
 const visible=useMemo(()=>options.filter(option=>option.label.toLocaleLowerCase("es").includes(search.trim().toLocaleLowerCase("es"))),[options,search]);
 useEffect(()=>{const close=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 function choose(id:string){onChange(id);setOpen(false);setSearch("")}
 return <div ref={root} className="relative min-w-0"><label className="font-semibold">{label}</label><button type="button" aria-haspopup="listbox" aria-expanded={open} aria-controls={listId} onClick={()=>setOpen(current=>!current)} className="mt-2 flex min-h-[54px] w-full items-center justify-between gap-3 rounded-xl border border-slate-300 bg-white px-4 py-3 text-left font-normal"><span className={`truncate ${selected?"text-slate-800":"text-slate-500"}`}>{selected?.label??placeholder}</span><span className="flex items-center gap-1">{value&&<span role="button" tabIndex={0} aria-label={`Limpiar ${label}`} onClick={event=>{event.stopPropagation();choose("")}} className="rounded p-1 text-slate-400 hover:bg-slate-100"><X size={14}/></span>}<ChevronDown size={18}/></span></button>{open&&<div id={listId} role="listbox" className="absolute z-[90] mt-2 w-full overflow-hidden rounded-xl border bg-white shadow-xl"><div className="flex items-center gap-2 border-b bg-slate-50 px-3"><Search size={16} className="text-slate-400"/><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} onKeyDown={event=>{if(event.key==="Escape")setOpen(false);if(event.key==="Enter"&&visible.length===1)choose(visible[0].id)}} placeholder={`Buscar ${label.toLowerCase()}`} className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/></div><div className="max-h-60 overflow-auto p-2">{visible.length?visible.map(option=><button type="button" role="option" aria-selected={option.id===value} key={option.id} onClick={()=>choose(option.id)} className="flex w-full items-center justify-between gap-3 rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50"><span>{option.label}</span>{option.id===value&&<Check size={16} className="shrink-0 text-red-700"/>}</button>):<p className="p-4 text-center text-sm text-slate-500">No hay coincidencias.</p>}</div></div>}</div>
}
