import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { PrismaService } from "../database/prisma.service";
@Injectable()
export class CatalogsRepository {
 constructor(private readonly prisma: PrismaService) {}
 private snapshot(v:unknown){return JSON.parse(JSON.stringify(v)) as Prisma.InputJsonValue}
 private code(v:unknown){const x=typeof v==="string"?v.trim().toUpperCase().replace(/[^A-Z0-9]+/g,"_"):"";if(!x)throw new BadRequestException("El código es obligatorio");return x}
 private date(v:unknown){if(!v)return null;const x=new Date(String(v));if(Number.isNaN(x.getTime()))throw new BadRequestException("Fecha inválida");return x}
 async list(code?:string){return this.prisma.catalog.findMany({where:{code:code?.trim().toUpperCase()||undefined},orderBy:{name:"asc"},include:{values:{orderBy:[{sortOrder:"asc"},{name:"asc"}]},_count:{select:{values:true}}}})}
 async impact(id:string){const value=await this.prisma.catalogValue.findUnique({where:{id},include:{catalog:true}});if(!value)throw new NotFoundException("No se encontró el valor");const counts=await Promise.all([this.prisma.person.count({where:{OR:[{occupationLevelId:id},{statusId:id}]}}),this.prisma.role.count({where:{OR:[{typeId:id},{statusId:id}]}}),this.prisma.team.count({where:{statusId:id}}),this.prisma.personRole.count({where:{OR:[{statusId:id},{onboardingStatusId:id}]}}),this.prisma.course.count({where:{OR:[{moduleId:id},{statusId:id}]}}),this.prisma.personCourse.count({where:{OR:[{statusId:id},{sourceId:id},{groupId:id}]}}),this.prisma.roleMaturity.count({where:{levelId:id}}),this.prisma.teamMaturity.count({where:{levelId:id}}),this.prisma.period.count({where:{statusId:id}}),this.prisma.objective.count({where:{OR:[{levelId:id},{focusAreaId:id},{cycleId:id},{directionId:id},{typeId:id},{unitId:id},{resultStatusId:id},{recordStatusId:id}]}}),this.prisma.initiative.count({where:{OR:[{cycleId:id},{focusAreaId:id},{levelId:id},{typeId:id},{sizeId:id},{priorityId:id},{managementTypeId:id},{statusId:id},{escalationId:id},{returnHorizonId:id},{tiCapacityId:id},{categoryId:id},{impactId:id},{executionAreaId:id}]}}),this.prisma.indicatorTarget.count({where:{OR:[{indicatorId:id},{scopeId:id},{unitId:id},{statusId:id}]}}),this.prisma.user.count({where:{OR:[{profileId:id},{statusId:id}]}})]);const labels=["personas","roles","equipos","asignaciones","cursos","avances formativos","madurez de roles","madurez de equipos","períodos","objetivos","iniciativas","metas","usuarios"];const dependencies=labels.map((label,index)=>({label,count:counts[index]})).filter(x=>x.count>0);return{id:value.id,catalog:value.catalog.name,value:value.name,total:counts.reduce((a,b)=>a+b,0),dependencies,canDeactivate:dependencies.length===0}}
 async create(catalogId:string,input:Record<string,unknown>,administratorId:string){const catalog=await this.prisma.catalog.findUnique({where:{id:catalogId}});if(!catalog)throw new NotFoundException("No se encontró el catálogo");const name=typeof input.name==="string"?input.name.trim():"";if(!name)throw new BadRequestException("El nombre es obligatorio");const data={catalogId,code:this.code(input.code),name,description:typeof input.description==="string"?input.description.trim()||null:null,sortOrder:Number(input.sortOrder)||0,active:input.active!==false,validFrom:this.date(input.validFrom),validUntil:this.date(input.validUntil)};if(data.validFrom&&data.validUntil&&data.validUntil<data.validFrom)throw new BadRequestException("La vigencia final no puede ser anterior a la inicial");try{return await this.prisma.$transaction(async tx=>{const value=await tx.catalogValue.create({data});await tx.audit.create({data:{occurredAt:new Date(),userId:administratorId,action:"CREATE",entity:"CATALOG_VALUE",recordId:value.id,newValue:this.snapshot(value),result:"OK",origin:"WEB"}});return value})}catch(e:unknown){if(typeof e==="object"&&e&&"code" in e&&e.code==="P2002")throw new BadRequestException("El código ya existe en este catálogo");throw e}}
 async update(id:string,input:Record<string,unknown>,administratorId:string){const current=await this.prisma.catalogValue.findUnique({where:{id}});if(!current)throw new NotFoundException("No se encontró el valor");const data:Prisma.CatalogValueUpdateInput={};if(input.name!==undefined){const name=typeof input.name==="string"?input.name.trim():"";if(!name)throw new BadRequestException("El nombre es obligatorio");data.name=name}if(input.description!==undefined)data.description=typeof input.description==="string"?input.description.trim()||null:null;if(input.sortOrder!==undefined){const order=Number(input.sortOrder);if(!Number.isInteger(order))throw new BadRequestException("El orden debe ser entero");data.sortOrder=order}if(input.active!==undefined)data.active=Boolean(input.active);if(input.validFrom!==undefined)data.validFrom=this.date(input.validFrom);if(input.validUntil!==undefined)data.validUntil=this.date(input.validUntil);const from=data.validFrom===undefined?current.validFrom:data.validFrom as Date|null,until=data.validUntil===undefined?current.validUntil:data.validUntil as Date|null;if(from&&until&&until<from)throw new BadRequestException("La vigencia final no puede ser anterior a la inicial");return this.prisma.$transaction(async tx=>{const value=await tx.catalogValue.update({where:{id},data});await tx.audit.create({data:{occurredAt:new Date(),userId:administratorId,action:"UPDATE",entity:"CATALOG_VALUE",recordId:id,oldValue:this.snapshot(current),newValue:this.snapshot(value),result:"OK",origin:"WEB"}});return value})}
}
