import { useCallback,useEffect,useMemo,useState } from "react";
import { apiUrl,demoHeaders,demoProfile } from "../directory/DirectoryShell";
type Role={id:string;sourceId:string;name:string;type:string;status:string;peopleCount:number;courses:{id:string;name:string;module:string}[]};type Course={id:string;sourceId:string;name:string;moduleId:string;statusId:string;module:string;status:string;roles:{id:string;name:string}[];progress:{person:string;status:string;score:number|null}[]};type Option={id:string;code:string;name:string};type Options={modules:Option[];statuses:Option[]};
const box="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm",input="rounded-xl border border-slate-300 px-4 py-3";
export function AcademyPage({view}:{view:"roles"|"courses"}){
 const admin=demoProfile==="ADMINISTRADOR",[roles,setRoles]=useState<Role[]>([]),[courses,setCourses]=useState<Course[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[roleId,setRoleId]=useState(""),[courseId,setCourseId]=useState(""),[options,setOptions]=useState<Options>({modules:[],statuses:[]}),[editing,setEditing]=useState<Course|null>(null),[showForm,setShowForm]=useState(false),[form,setForm]=useState({sourceId:"",name:"",moduleId:"",statusId:""});
 const load=useCallback(async()=>{setLoading(true);try{const [roleResponse,courseResponse]=await Promise.all([fetch(`${apiUrl}/api/academy/roles`,{headers:demoHeaders}),fetch(`${apiUrl}/api/academy/courses`,{headers:demoHeaders})]);if(!roleResponse.ok||!courseResponse.ok)throw new Error("No se pudo cargar la academia");setRoles(await roleResponse.json());setCourses(await courseResponse.json())}catch(error){setMessage(error instanceof Error?error.message:"Error inesperado")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();if(admin)fetch(`${apiUrl}/api/academy/admin/options`,{headers:demoHeaders}).then(response=>response.ok?response.json():Promise.reject()).then(setOptions).catch(()=>setMessage("No se cargaron las opciones administrativas."))},[admin,load]);const selectedRole=useMemo(()=>roles.find(role=>role.id===roleId),[roleId,roles]);
 async function assign(){if(!roleId||!courseId)return;const response=await fetch(`${apiUrl}/api/academy/roles/${roleId}/courses/${courseId}`,{method:"POST",headers:{...demoHeaders,"Content-Type":"application/json"}});if(!response.ok){setMessage("No se pudo asignar el curso.");return}setMessage("Curso asignado correctamente.");setCourseId("");await load()}
 async function unassign(role:string,course:string){if(!window.confirm("¿Desvincular este curso del rol? Ya no se generará para nuevas asignaciones."))return;const response=await fetch(`${apiUrl}/api/academy/roles/${role}/courses/${course}/deactivate`,{method:"PATCH",headers:demoHeaders});if(!response.ok){setMessage("No se pudo desvincular el curso.");return}setMessage("Curso desvinculado correctamente.");await load()}
 function edit(course?:Course){setEditing(course??null);setShowForm(true);setForm(course?{sourceId:course.sourceId,name:course.name,moduleId:course.moduleId,statusId:course.statusId}:{sourceId:"",name:"",moduleId:options.modules[0]?.id??"",statusId:options.statuses.find(option=>option.code==="ACTIVO")?.id??options.statuses[0]?.id??""})}
 async function save(){const response=await fetch(`${apiUrl}/api/academy/courses${editing?`/${editing.id}`:""}`,{method:editing?"PATCH":"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json().catch(()=>({}));if(!response.ok){setMessage(body.message??"No se pudo guardar el curso.");return}setMessage(editing?"Curso actualizado correctamente.":"Curso creado correctamente.");setShowForm(false);await load()}
 return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="/" className="text-lg font-bold">Mochelab <span className="text-emerald-600">2.0</span></a><nav className="flex gap-2"><a href="/roles" className="rounded-lg px-4 py-2 font-bold">Roles</a><a href="/cursos" className="rounded-lg px-4 py-2 font-bold">Cursos</a></nav></div></header><div className="mx-auto max-w-7xl px-5 py-8"><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">Academia</p><h1 className="mt-2 text-3xl font-bold">{view==="roles"?"Roles y formación requerida":"Cursos y avance"}</h1><p className="mt-3 text-slate-600">{view==="roles"?(admin?"Define los cursos que corresponden a cada rol.":"Consulta la formación requerida para cada rol."):"Consulta cursos, roles asociados y avance."}</p>
 {admin&&view==="roles"&&<section className={`mt-8 ${box}`}><h2 className="text-lg font-bold">Asignar curso a un rol</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select aria-label="Rol" value={roleId} onChange={event=>setRoleId(event.target.value)} className={input}><option value="">Selecciona un rol</option>{roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select><select aria-label="Curso" value={courseId} onChange={event=>setCourseId(event.target.value)} className={input}><option value="">Selecciona un curso</option>{courses.filter(course=>!selectedRole?.courses.some(item=>item.id===course.id)).map(course=><option key={course.id} value={course.id}>{course.name}</option>)}</select><button disabled={!roleId||!courseId} onClick={()=>void assign()} className="rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white disabled:bg-slate-300">Asignar</button></div></section>}
 {admin&&view==="courses"&&<section className={`mt-8 ${box}`}><div className="flex justify-between"><h2 className="text-lg font-bold">Catálogo de cursos</h2><button onClick={()=>edit()} className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">Nuevo curso</button></div>{showForm&&<div className="mt-4 grid gap-3 md:grid-cols-2"><input aria-label="Código" placeholder="Código" value={form.sourceId} onChange={event=>setForm({...form,sourceId:event.target.value})} className={input}/><input aria-label="Nombre" placeholder="Nombre" value={form.name} onChange={event=>setForm({...form,name:event.target.value})} className={input}/><select aria-label="Módulo" value={form.moduleId} onChange={event=>setForm({...form,moduleId:event.target.value})} className={input}>{options.modules.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select><select aria-label="Estado" value={form.statusId} onChange={event=>setForm({...form,statusId:event.target.value})} className={input}>{options.statuses.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select><div className="flex gap-2"><button disabled={!form.sourceId||!form.name||!form.moduleId||!form.statusId} onClick={()=>void save()} className="rounded-xl bg-slate-950 px-4 py-2 font-bold text-white disabled:bg-slate-300">Guardar</button><button onClick={()=>setShowForm(false)} className="rounded-xl border px-4 py-2 font-bold">Cancelar</button></div></div>}</section>}
 {message&&<p className="mt-5 rounded-xl bg-amber-100 p-4 font-semibold">{message}</p>}{loading?<p className="mt-8">Cargando…</p>:<section className="mt-8 grid gap-5 md:grid-cols-2">{view==="roles"?roles.map(role=><article key={role.id} className={box}><div className="flex justify-between"><div><h2 className="text-lg font-bold">{role.name}</h2><p className="text-sm text-slate-500">{role.type} · {role.peopleCount} persona(s)</p></div><span>{role.status}</span></div><h3 className="mt-5 border-t pt-4 font-bold">Cursos requeridos</h3>{role.courses.length?role.courses.map(course=><div key={course.id} className="mt-3 flex justify-between text-sm"><span>{course.name} · {course.module}</span>{admin&&<button onClick={()=>void unassign(role.id,course.id)} className="font-bold text-rose-700">Desvincular</button>}</div>):<p className="mt-3 text-sm text-slate-500">Sin cursos asignados</p>}</article>):courses.map(course=><article key={course.id} className={box}><div className="flex justify-between"><div><h2 className="text-lg font-bold">{course.name}</h2><p className="text-sm text-emerald-700">{course.sourceId} · {course.module}</p></div>{admin&&<button onClick={()=>edit(course)} className="rounded-lg border px-3 py-1 font-bold">Editar</button>}</div><p className="mt-4 text-sm"><strong>Roles:</strong> {course.roles.map(role=>role.name).join(", ")||"Sin roles"}</p></article>)}</section>}</div></main>;
}
