import { useCallback, useEffect, useState } from "react";
import { apiUrl, demoHeaders, demoProfile } from "../directory/DirectoryShell";
type Progress={personRoleId:string;courseId:string;person:string;status:string;statusName:string;score:number|null;startDate:string|null;endDate:string|null};type Course={id:string;name:string;module:string;progress:Progress[]};
export function CourseProgressPage(){
 const admin=demoProfile==="ADMINISTRADOR",[courses,setCourses]=useState<Course[]>([]),[selected,setSelected]=useState<Progress|null>(null),[status,setStatus]=useState("PENDIENTE"),[score,setScore]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const response=await fetch(`${apiUrl}/api/academy/courses`,{headers:demoHeaders});if(!response.ok){setMessage("No se pudo cargar el avance formativo.");setLoading(false);return}setCourses(await response.json());setLoading(false)},[]);useEffect(()=>{void load()},[load]);
 function edit(item:Progress){setSelected(item);setStatus(item.status);setScore(item.score?.toString()??"");setStartDate(item.startDate??"");setEndDate(item.endDate??"");setMessage("")}
 async function save(){if(!selected)return;const response=await fetch(`${apiUrl}/api/academy/person-roles/${selected.personRoleId}/courses/${selected.courseId}`,{method:"PATCH",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify({statusCode:status,score:score===""?null:Number(score),startDate:startDate||null,endDate:endDate||null})});const body=await response.json().catch(()=>({}));if(!response.ok){setMessage(body.message??"No se pudo guardar el avance.");return}setMessage("Avance guardado correctamente.");setSelected(null);await load()}
 return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="/" className="text-lg font-bold">Mochelab <span className="text-emerald-600">2.0</span></a></div></header><div className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Academia</p><h1 className="mt-2 text-3xl font-bold">Avance formativo</h1><p className="mt-3 text-slate-600">{admin?"Actualiza el estado, nota y fechas de cada curso asignado.":"Consulta el estado, nota y fechas de tus cursos asignados."}</p>
 {admin&&selected&&<section className="mt-8 rounded-2xl border border-emerald-300 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">{selected.person}</h2><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-5"><select aria-label="Estado" value={status} onChange={event=>setStatus(event.target.value)} className="rounded-xl border px-3 py-3"><option value="PENDIENTE">Pendiente</option><option value="TERMINADO">Terminado</option></select><input aria-label="Nota" type="number" min="0" max="20" step="0.01" value={score} onChange={event=>setScore(event.target.value)} className="rounded-xl border px-3 py-3"/><input aria-label="Fecha de inicio" type="date" value={startDate} onChange={event=>setStartDate(event.target.value)} className="rounded-xl border px-3 py-3"/><input aria-label="Fecha de fin" type="date" value={endDate} onChange={event=>setEndDate(event.target.value)} className="rounded-xl border px-3 py-3"/><button onClick={()=>void save()} className="rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">Guardar</button></div></section>}
 {message&&<p className="mt-5 rounded-xl bg-rose-100 p-4 font-semibold text-rose-800">{message}</p>}{loading?<p className="mt-8 text-slate-500">Cargando…</p>:<section className="mt-8 space-y-5">{courses.map(course=><article key={course.id} className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">{course.name}</h2><p className="mt-1 text-sm text-emerald-700">{course.module}</p>{course.progress.length?course.progress.map(item=><div key={item.personRoleId} className="mt-4 grid gap-3 border-t pt-4 sm:grid-cols-[1fr_auto_auto]"><div><strong>{item.person}</strong><p className="mt-1 text-sm text-slate-500">{item.startDate??"Sin inicio"} — {item.endDate??"Sin fin"}</p></div><span className="font-semibold">{item.statusName}{item.score==null?"":` · Nota ${item.score}`}</span>{admin&&<button onClick={()=>edit(item)} className="rounded-lg border border-emerald-600 px-4 py-2 text-sm font-bold text-emerald-700">Editar</button>}</div>):<p className="mt-4 text-sm text-slate-500">Sin personas asignadas.</p>}</article>)}</section>}</div></main>;
}
