import {useEffect,useMemo,useRef,useState} from "react";
import {downloadCsv} from "../utils/csv";
import {defaultRoleFilterIds} from "../utils/defaultRoleFilters";
import {apiUrl,demoHeaders,DirectoryShell} from "./DirectoryShell";
import {useModuleCapability} from "../access/useModuleCapability";
import {MultiSelect} from "../components/MultiSelect";
type Option={id:string;label:string;code?:string};
type Row={id:string;person:{id:string;names:string;dni:string;company:{name:string}};role:{name:string};team:{id:string;sourceId:string;program:{name:string}};status:{id:string;name:string};onboardingStatus:{id:string;name:string};startDate:string|null;endDate:string|null;_count:{courses:number}};
type Result={id:string;ok:boolean;message:string};
type Options={people:Option[];roles:Option[];teams:Option[];assignmentStatuses:Option[];onboardingStatuses:Option[]};
const emptyOptions:Options={people:[],roles:[],teams:[],assignmentStatuses:[],onboardingStatuses:[]};

export function AssignmentsPage(){
 const capability=useModuleCapability("ASIGNACIONES");
 const roleDefaultsInitialized=useRef(false);
 const loadRequest=useRef(0);
 const[rows,setRows]=useState<Row[]>([]),[options,setOptions]=useState<Options>(emptyOptions),[selected,setSelected]=useState<string[]>([]),[failed,setFailed]=useState<Result[]>([]),[search,setSearch]=useState(""),[teamIds,setTeamIds]=useState<string[]>([]),[roleFilters,setRoleFilters]=useState<string[]>([]),[filterStatuses,setFilterStatuses]=useState<string[]>([]),[onboardingFilters,setOnboardingFilters]=useState<string[]>([]),[filtersOpen,setFiltersOpen]=useState(false),[statusId,setStatusId]=useState(""),[onboardingStatusId,setOnboardingStatusId]=useState(""),[message,setMessage]=useState(""),[page,setPage]=useState(1),[showCreate,setShowCreate]=useState(false),[personId,setPersonId]=useState(""),[roleId,setRoleId]=useState(""),[newTeamId,setNewTeamId]=useState(""),[saving,setSaving]=useState(false);const pageSize=25;
 async function loadOptions(){const response=await fetch(`${apiUrl}/api/assignment-options`,{headers:demoHeaders});if(!response.ok){setMessage("No se pudieron cargar las opciones de asignación.");return}const nextOptions=await response.json() as Options;setOptions(nextOptions);if(!roleDefaultsInitialized.current){roleDefaultsInitialized.current=true;setRoleFilters(defaultRoleFilterIds(nextOptions.roles,item=>item.id,item=>item.label))}setFilterStatuses(current=>{if(current.length)return current;const active=nextOptions.assignmentStatuses.find(item=>item.code==="ACTIVO");return active?[active.id]:[]})}
 async function load(){const request=++loadRequest.current,q=new URLSearchParams();if(search)q.set("search",search);if(teamIds.length)q.set("teamIds",teamIds.join(","));if(roleFilters.length)q.set("roleIds",roleFilters.join(","));if(filterStatuses.length)q.set("statusIds",filterStatuses.join(","));if(onboardingFilters.length)q.set("onboardingStatusIds",onboardingFilters.join(","));const response=await fetch(`${apiUrl}/api/person-role-assignments?${q}`,{headers:demoHeaders});if(request!==loadRequest.current)return;if(response.ok){setRows(await response.json());setMessage("")}else setMessage("No se pudieron cargar las asignaciones. Intenta actualizar la página.");setPage(1)}
 useEffect(()=>{void loadOptions()},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[search,teamIds,roleFilters,filterStatuses,onboardingFilters]);
 function toggle(id:string){setSelected(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id])}
 async function update(ids=selected){if(!capability?.canEdit){setMessage("Tu perfil no tiene permiso para modificar asignaciones.");return}setMessage("");const response=await fetch(`${apiUrl}/api/person-role-assignments`,{method:"PATCH",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify({ids,statusId:statusId||undefined,onboardingStatusId:onboardingStatusId||undefined})});const body=await response.json();if(!response.ok){setMessage(body.message??"No se pudo realizar la actualización.");return}setFailed(body.results.filter((item:Result)=>!item.ok));setMessage(`${body.succeeded} actualizada(s); ${body.failed} con error.`);setSelected([]);await load()}
 async function createAssignment(){if(!capability?.canCreate){setMessage("Tu perfil no tiene permiso para crear asignaciones.");return}setSaving(true);setMessage("");const response=await fetch(`${apiUrl}/api/person-role-assignments`,{method:"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify({personId,roleId,teamId:newTeamId})});const body=await response.json().catch(()=>({}));setSaving(false);if(!response.ok){setMessage(body.message??"No se pudo crear la asignación.");return}setMessage(`Asignación creada. Se generaron ${body.generatedCourses??0} curso(s) pendientes.`);setShowCreate(false);setPersonId("");setRoleId("");setNewTeamId("");await load()}
 const filteredRows=useMemo(()=>rows.filter(item=>(teamIds.length===0||teamIds.includes(item.team.id))&&(roleFilters.length===0||roleFilters.some(id=>options.roles.find(option=>option.id===id)?.label===item.role.name))&&(filterStatuses.length===0||filterStatuses.includes(item.status.id))&&(onboardingFilters.length===0||onboardingFilters.includes(item.onboardingStatus.id))),[rows,teamIds,roleFilters,filterStatuses,onboardingFilters,options]);
 function exportRows(){downloadCsv("asignaciones.csv",["Persona","DNI","Empresa","Rol","Equipo","Programa","Estado","Onboarding","Inicio","Fin","Cursos"],filteredRows.map(item=>[item.person.names,item.person.dni,item.person.company.name,item.role.name,item.team.sourceId,item.team.program.name,item.status.name,item.onboardingStatus.name,item.startDate,item.endDate,item._count.courses]))}
 const pages=Math.max(1,Math.ceil(filteredRows.length/pageSize)),visible=useMemo(()=>filteredRows.slice((page-1)*pageSize,page*pageSize),[filteredRows,page]);
 const activeCount=filteredRows.filter(item=>item.status.name.trim().toUpperCase()==="ACTIVO").length,pendingOnboarding=filteredRows.filter(item=>item.onboardingStatus.name.trim().toUpperCase()!=="TERMINADO").length,withoutStart=filteredRows.filter(item=>!item.startDate).length,attentionCount=filteredRows.filter(item=>item.status.name.trim().toUpperCase()!=="ACTIVO"||item.onboardingStatus.name.trim().toUpperCase()!=="TERMINADO"||!item.startDate).length;
 useEffect(()=>setPage(1),[teamIds,roleFilters,filterStatuses,onboardingFilters]);
 return <DirectoryShell title="Personas" description="Consulta colaboradores y gestiona sus roles, equipos y estado de incorporación." active="assignments">
  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AssignmentKpi label="Asignaciones activas" value={activeCount} tone="green"/><AssignmentKpi label="Onboarding pendiente" value={pendingOnboarding} tone="amber"/><AssignmentKpi label="Sin fecha de inicio" value={withoutStart} tone="blue"/><AssignmentKpi label="Requieren atención" value={attentionCount} tone="red"/></section>
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={()=>setFiltersOpen(!filtersOpen)} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold">Filtros{(teamIds.length+roleFilters.length+filterStatuses.length+onboardingFilters.length+(search?1:0))>0&&<span className="ml-2 rounded-full bg-red-50 px-2 py-0.5 text-xs text-red-700">{teamIds.length+roleFilters.length+filterStatuses.length+onboardingFilters.length+(search?1:0)}</span>}</button>{(teamIds.length+roleFilters.length+filterStatuses.length+onboardingFilters.length+(search?1:0))>0&&<button type="button" onClick={()=>{setSearch("");setTeamIds([]);setRoleFilters([]);setFilterStatuses([]);setOnboardingFilters([])}} className="text-sm font-bold text-red-700">Limpiar filtros</button>}</div>{filtersOpen&&<div className="mt-4 grid gap-3 border-t pt-4 sm:grid-cols-2"><MultiSelect label="Roles" emptyLabel="Todos los roles" value={roleFilters} onChange={setRoleFilters} options={options.roles}/><MultiSelect label="Onboarding" emptyLabel="Todos los estados de onboarding" value={onboardingFilters} onChange={setOnboardingFilters} options={options.onboardingStatuses}/></div>}</section>
  <div className="mt-6 flex flex-wrap justify-end gap-3"><button onClick={exportRows} className="rounded-xl border border-slate-300 bg-white px-4 py-2 font-bold">Exportar</button>{capability?.canCreate&&<button onClick={()=>setShowCreate(true)} className="brand-action rounded-xl px-5 py-2 font-bold">Nueva asignación</button>}</div>
  {showCreate&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/55 p-4" role="dialog" aria-modal="true" aria-labelledby="new-assignment-title"><section className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-red-700">Personas y equipos</p><h2 id="new-assignment-title" className="mt-1 text-2xl font-bold">Nueva asignación</h2><p className="mt-2 text-slate-600">Asigna un rol dentro de un equipo. La malla formativa se generará automáticamente.</p></div><button onClick={()=>setShowCreate(false)} className="rounded-lg px-3 py-2 text-xl text-slate-500" aria-label="Cerrar">×</button></div><div className="mt-6 grid gap-4"><label className="font-semibold">Persona<select value={personId} onChange={e=>setPersonId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal"><option value="">Selecciona una persona</option>{options.people.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><div className="grid gap-4 md:grid-cols-2"><label className="font-semibold">Rol<select value={roleId} onChange={e=>setRoleId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal"><option value="">Selecciona un rol</option>{options.roles.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label className="font-semibold">Equipo<select value={newTeamId} onChange={e=>setNewTeamId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal"><option value="">Selecciona un equipo</option>{options.teams.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label></div></div><div className="mt-6 flex justify-end gap-3 border-t pt-5"><button onClick={()=>setShowCreate(false)} className="rounded-xl px-5 py-3 font-bold text-slate-600">Cancelar</button><button disabled={!personId||!roleId||!newTeamId||saving} onClick={()=>void createAssignment()} className="brand-action rounded-xl px-6 py-3 font-bold disabled:opacity-40">{saving?"Guardando…":"Crear asignación"}</button></div></section></div>}
  <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{filtersOpen&&<div className="grid gap-3 md:grid-cols-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Persona, DNI, rol o equipo" className="control"/><MultiSelect label="Equipos" emptyLabel="Todos los equipos" value={teamIds} onChange={setTeamIds} options={options.teams}/><MultiSelect label="Estados" emptyLabel="Todos los estados" value={filterStatuses} onChange={setFilterStatuses} options={options.assignmentStatuses}/></div>}<div className="mt-4 flex flex-wrap gap-3"><select value={statusId} onChange={e=>setStatusId(e.target.value)} className="rounded-xl border px-3 py-2"><option value="">No cambiar asignación</option>{options.assignmentStatuses.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select value={onboardingStatusId} onChange={e=>setOnboardingStatusId(e.target.value)} className="rounded-xl border px-3 py-2"><option value="">No cambiar onboarding</option>{options.onboardingStatuses.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><button disabled={!selected.length||(!statusId&&!onboardingStatusId)} onClick={()=>void update()} className="brand-action rounded-xl px-4 py-2 font-bold disabled:bg-slate-300">Actualizar {selected.length} seleccionada(s)</button>{failed.length>0&&<button onClick={()=>void update(failed.map(x=>x.id))} className="rounded-xl bg-amber-600 px-4 py-2 font-bold text-white">Reintentar {failed.length} fallida(s)</button>}</div>{message&&<p className="mt-3 font-semibold text-slate-700">{message}</p>}</section>
  <section className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4"><input aria-label="Seleccionar página" type="checkbox" checked={visible.length>0&&visible.every(x=>selected.includes(x.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(x=>x.id)])]:selected.filter(id=>!visible.some(x=>x.id===id)))}/></th><th>Persona</th><th>Rol y equipo</th><th>Estado</th><th>Onboarding</th><th>Cursos</th></tr></thead><tbody>{visible.map(x=><tr key={x.id} className="border-t"><td className="p-4"><input aria-label={`Seleccionar ${x.person.names}`} type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/></td><td><a className="brand-link font-bold" href={`/personas/${x.person.id}`}>{x.person.names}</a><div className="text-slate-500">{x.person.dni} · {x.person.company.name}</div></td><td><strong>{x.role.name}</strong><div className="text-slate-500">{x.team.sourceId} · {x.team.program.name}</div></td><td>{x.status.name}</td><td>{x.onboardingStatus.name}</td><td>{x._count.courses}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-slate-500">No se encontraron asignaciones.</p>}</section><div className="mt-4 flex justify-end gap-3"><button disabled={page===1} onClick={()=>setPage(page-1)} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Anterior</button><span className="py-2 text-sm font-bold">Página {page} de {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Siguiente</button></div>
 </DirectoryShell>
}
function AssignmentKpi({label,value,tone}:{label:string;value:number;tone:"green"|"amber"|"blue"|"red"}){const colors={green:"border-emerald-200 bg-emerald-50 text-emerald-800",amber:"border-amber-200 bg-amber-50 text-amber-900",blue:"border-blue-200 bg-blue-50 text-blue-900",red:"border-red-200 bg-red-50 text-red-900"};return <article className={`rounded-2xl border p-5 ${colors[tone]}`}><p className="text-sm font-semibold">{label}</p><strong className="mt-2 block text-3xl">{value}</strong><span className="text-xs opacity-70">Según los filtros aplicados</span></article>}
