import { useEffect, useMemo, useState, type ReactNode } from "react";
import { apiUrl, demoHeaders } from "./DirectoryShell";

type O={id:string;code:string;name:string};
type Unit=O&{companyId:string;unitType?:string;parentId?:string|null};
type Options={companies:O[];units:Unit[];programs:O[];businessPartners:O[];catalogs:Record<string,O[]>};
type Person={id:string;dni:string;names:string;email:string|null;phone:string|null;position:string|null;company:string;companyId:string;occupationLevelId:string|null;organizationalUnitId:string|null;businessPartnerId:string|null;status:string;statusId:string};
type Team={id:string;sourceId:string;name:string;program:string;programId:string;unitId:string|null;status:string;statusId:string};
type Role={id:string;sourceId:string;name:string;type:string;typeId:string;status:string;statusId:string;peopleCount:number};
type Course={id:string;sourceId:string;name:string;module:string;moduleId:string;status:string;statusId:string;roles:{id:string;name:string}[]};
type Kind="personas"|"equipos"|"roles"|"cursos";
const blanks={personas:{dni:"",names:"",email:"",phone:"",position:"",companyId:"",occupationLevelId:"",organizationalUnitId:"",businessPartnerId:"",statusId:""},equipos:{sourceId:"",programId:"",unitId:"",statusId:""},roles:{sourceId:"",name:"",typeId:"",statusId:""},cursos:{sourceId:"",name:"",moduleId:"",statusId:""}};

export function MasterDataPage(){
 const[kind,setKind]=useState<Kind>("personas"),[options,setOptions]=useState<Options|null>(null),[people,setPeople]=useState<Person[]>([]),[teams,setTeams]=useState<Team[]>([]),[roles,setRoles]=useState<Role[]>([]),[courses,setCourses]=useState<Course[]>([]),[form,setForm]=useState<Record<string,string>>(blanks.personas),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState("");
 async function load(){setBusy(true);const responses=await Promise.all([fetch(apiUrl+"/api/directory-admin/options",{headers:demoHeaders}),fetch(apiUrl+"/api/people",{headers:demoHeaders}),fetch(apiUrl+"/api/teams",{headers:demoHeaders}),fetch(apiUrl+"/api/academy/roles",{headers:demoHeaders}),fetch(apiUrl+"/api/academy/courses",{headers:demoHeaders})]);if(responses.some(x=>!x.ok)){setMessage("No se pudieron cargar los maestros. Verifica el perfil administrador.");setBusy(false);return}setOptions(await responses[0].json());setPeople(await responses[1].json());setTeams(await responses[2].json());setRoles(await responses[3].json());setCourses(await responses[4].json());setBusy(false)}
 useEffect(()=>{void load()},[]);
 function start(next:Kind){setKind(next);setEditing(null);setMessage("");const base={...blanks[next]};const catalog=next==="personas"?"ESTADO_PERSONA":next==="equipos"?"ESTADO_EQUIPO":next==="roles"?"ESTADO_ROL":"ESTADO_CURSO";base.statusId=options?.catalogs[catalog]?.find(x=>x.code==="ACTIVO")?.id||"";setForm(base)}
 function edit(row:Person|Team|Role|Course){setEditing(row.id);if(kind==="personas"){const x=row as Person;setForm({dni:x.dni,names:x.names,email:x.email||"",phone:x.phone||"",position:x.position||"",companyId:x.companyId,occupationLevelId:x.occupationLevelId||"",organizationalUnitId:x.organizationalUnitId||"",businessPartnerId:x.businessPartnerId||"",statusId:x.statusId})}else if(kind==="equipos"){const x=row as Team;setForm({sourceId:x.sourceId,programId:x.programId,unitId:x.unitId||"",statusId:x.statusId})}else if(kind==="roles"){const x=row as Role;setForm({sourceId:x.sourceId,name:x.name,typeId:x.typeId,statusId:x.statusId})}else{const x=row as Course;setForm({sourceId:x.sourceId,name:x.name,moduleId:x.moduleId,statusId:x.statusId})}window.scrollTo({top:0,behavior:"smooth"})}
 const set=(key:string,value:string)=>setForm(x=>({...x,[key]:value}));
 async function save(){setBusy(true);setMessage("");const path=kind==="personas"?"people":kind==="equipos"?"teams":kind==="roles"?"roles":"academy/courses";const response=await fetch(`${apiUrl}/api/${path}${editing?`/${editing}`:""}`,{method:editing?"PATCH":"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json().catch(()=>({}));if(!response.ok){setMessage(typeof body.message==="string"?body.message:"No se pudo guardar");setBusy(false);return}setMessage(editing?"Registro actualizado.":"Registro creado.");setEditing(null);await load()}
 const rows=(kind==="personas"?people:kind==="equipos"?teams:kind==="roles"?roles:courses).filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase()));
 const optional=["email","phone","position","occupationLevelId","organizationalUnitId","businessPartnerId","unitId"];
 const valid=Object.entries(form).every(([key,value])=>Boolean(value)||optional.includes(key));
 const companyUnits=useMemo(()=>options?.units.filter(x=>!form.companyId||x.companyId===form.companyId)??[],[options,form.companyId]);
 return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl justify-between px-5 py-4"><a href="/" className="font-bold">Mochelab <span className="text-red-700">2.0</span></a><b>Administrador</b></div></header><div className="mx-auto max-w-7xl px-5 py-8"><p className="text-sm font-bold uppercase tracking-wider text-red-700">Configuración</p><h1 className="mt-2 text-3xl font-bold">Maestros organizacionales</h1><div className="mt-6 flex flex-wrap gap-2">{(["personas","equipos","roles","cursos"] as Kind[]).map(x=><button key={x} onClick={()=>start(x)} className={`rounded-full px-4 py-2 font-bold capitalize ${kind===x?"bg-slate-950 text-white":"border bg-white text-slate-600"}`}>{x}</button>)}</div>
 {options&&<section className="mt-6 rounded-2xl border bg-white p-6 shadow-sm"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-red-700">{editing?"Edición":"Nuevo registro"}</p><h2 className="mt-1 text-xl font-bold">{kind.slice(0,-1)}</h2></div><button onClick={()=>start(kind)} className="brand-link text-sm font-bold">Limpiar</button></div>
 {kind==="personas"&&<div className="mt-5 space-y-6"><FormGroup title="Identificación"><Field label="DNI" value={form.dni} onChange={v=>set("dni",v)}/><Field label="Nombres completos" value={form.names} onChange={v=>set("names",v)}/><Select label="Empresa" value={form.companyId} options={options.companies} onChange={v=>{set("companyId",v);set("organizationalUnitId","")}}/><Field label="Correo" value={form.email} type="email" optional onChange={v=>set("email",v)}/><Field label="Teléfono" value={form.phone} optional onChange={v=>set("phone",v)}/></FormGroup><FormGroup title="Información laboral"><Field label="Posición / puesto" value={form.position} optional onChange={v=>set("position",v)}/><Select label="Nivel ocupacional" value={form.occupationLevelId} options={options.catalogs.NIVEL_OCUPACIONAL||[]} optional onChange={v=>set("occupationLevelId",v)}/><Select label="Gerencia / subgerencia / división" value={form.organizationalUnitId} options={companyUnits} optional onChange={v=>set("organizationalUnitId",v)}/><Select label="Business partner" value={form.businessPartnerId} options={options.businessPartners} optional onChange={v=>set("businessPartnerId",v)}/><Select label="Estado" value={form.statusId} options={options.catalogs.ESTADO_PERSONA||[]} onChange={v=>set("statusId",v)}/></FormGroup></div>}
 {kind==="equipos"&&<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Código" value={form.sourceId} onChange={v=>set("sourceId",v)}/><Select label="Programa" value={form.programId} options={options.programs} onChange={v=>set("programId",v)}/><Select label="Unidad" value={form.unitId} options={options.units} optional onChange={v=>set("unitId",v)}/><Select label="Estado" value={form.statusId} options={options.catalogs.ESTADO_EQUIPO||[]} onChange={v=>set("statusId",v)}/></div>}
 {kind==="roles"&&<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Código" value={form.sourceId} onChange={v=>set("sourceId",v)}/><Field label="Nombre" value={form.name} onChange={v=>set("name",v)}/><Select label="Tipo" value={form.typeId} options={options.catalogs.TIPO_ROL||[]} onChange={v=>set("typeId",v)}/><Select label="Estado" value={form.statusId} options={options.catalogs.ESTADO_ROL||[]} onChange={v=>set("statusId",v)}/></div>}
 {kind==="cursos"&&<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Código" value={form.sourceId} onChange={v=>set("sourceId",v)}/><Field label="Nombre" value={form.name} onChange={v=>set("name",v)}/><Select label="Módulo" value={form.moduleId} options={options.catalogs.MODULO_CURSO||[]} onChange={v=>set("moduleId",v)}/><Select label="Estado" value={form.statusId} options={options.catalogs.ESTADO_CURSO||[]} onChange={v=>set("statusId",v)}/></div>}
 <div className="mt-6 flex justify-end"><button disabled={busy||!valid} onClick={()=>void save()} className="brand-action rounded-xl px-7 py-3 font-bold disabled:opacity-40">{busy?"Guardando…":editing?"Guardar cambios":"Crear registro"}</button></div></section>}
 {message&&<p className="mt-5 rounded-xl bg-amber-50 p-4 font-semibold text-amber-900">{message}</p>}<section className="mt-6 overflow-hidden rounded-2xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><b>{rows.length} registro(s)</b><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en el maestro" className="w-full rounded-xl border px-4 py-2 sm:w-80"/></div><div className="hidden grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] bg-slate-50 sm:grid px-5 py-3 text-sm font-bold text-slate-500"><span>Registro</span><span>Estado / detalle</span><span>Acción</span></div>{rows.map(row=><div key={row.id} className="grid grid-cols-1 gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] sm:items-center border-t px-5 py-4"><div><b>{"names" in row?row.names:row.name}</b><p className="text-sm text-slate-500">{"dni" in row?`${row.dni} · ${row.company}`:row.sourceId}</p></div><span>{row.status}{"peopleCount" in row?` · ${row.peopleCount} persona(s)`:"program" in row?` · ${row.program}`:"module" in row?` · ${row.module}`:""}</span><button onClick={()=>edit(row)} className="rounded-lg border px-3 py-2 text-sm font-bold">Editar</button></div>)}</section></div></main>}

function FormGroup({title,children}:{title:string;children:ReactNode}){return <fieldset><legend className="mb-3 text-sm font-extrabold uppercase tracking-wide text-slate-500">{title}</legend><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{children}</div></fieldset>}
function Field({label,value,onChange,optional=false,type="text"}:{label:string;value:string;onChange:(value:string)=>void;optional?:boolean;type?:string}){return <label className="text-sm font-bold">{label}{optional&&<span className="ml-1 font-normal text-slate-400">(opcional)</span>}<input type={type} value={value||""} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 text-base font-normal"/></label>}
function Select({label,value,options,onChange,optional=false}:{label:string;value:string;options:O[];onChange:(value:string)=>void;optional?:boolean}){return <label className="text-sm font-bold">{label}{optional&&<span className="ml-1 font-normal text-slate-400">(opcional)</span>}<select value={value||""} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3 text-base font-normal"><option value="">{optional?"Sin asignar":"Selecciona"}</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
