import { useCallback,useEffect,useRef,useState } from "react";
import { apiUrl,demoHeaders,DirectoryShell } from "./DirectoryShell";
import { MultiSelect,type MultiSelectOption } from "../components/MultiSelect";
import { defaultRoleFilterIds } from "../utils/defaultRoleFilters";
import { EmptyState,ErrorState,LoadingState } from "../components/AsyncState";
type Team={id:string;sourceId:string;program:string;unit:string|null;company:string|null;status:string;members:{name:string;role:string}[]};type Response={items:Team[];total:number;page:number;pageSize:number;pages:number};
export function TeamsPage(){const initialized=useRef(false),[teams,setTeams]=useState<Team[]>([]),[search,setSearch]=useState(""),[roleIds,setRoleIds]=useState<string[]>([]),[roleOptions,setRoleOptions]=useState<MultiSelectOption[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0);const pageSize=20;
 useEffect(()=>{fetch(`${apiUrl}/api/team-filter-options`,{headers:demoHeaders}).then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<{roles:MultiSelectOption[]}>}).then(data=>{setRoleOptions(data.roles);if(!initialized.current){initialized.current=true;setRoleIds(defaultRoleFilterIds(data.roles,item=>item.id,item=>item.label))}}).catch(()=>setError("No se pudieron cargar las opciones de roles."))},[]);
 const load=useCallback(()=>{setLoading(true);setError("");const query=new URLSearchParams({search,page:String(page),pageSize:String(pageSize)});if(roleIds.length)query.set("roles",roleIds.join(","));fetch(`${apiUrl}/api/teams?${query}`,{headers:demoHeaders}).then(async response=>{if(!response.ok)throw new Error("No se pudieron cargar los equipos");return response.json() as Promise<Response>}).then(data=>{setTeams(data.items);setTotal(data.total);setPages(data.pages)}).catch(reason=>setError(reason instanceof Error?reason.message:"Error inesperado")).finally(()=>setLoading(false))},[search,roleIds,page]);useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);useEffect(()=>setPage(1),[search,roleIds]);
 return <DirectoryShell title="Equipos" description="Consulta equipos, programas y las personas que desempeñan cada rol." active="teams"><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-3 border-b border-slate-200 p-5 md:grid-cols-2"><div className="flex items-center"><strong>{loading?"Consultando…":`${total} equipo${total===1?"":"s"}`}</strong></div><label><span className="sr-only">Buscar equipos</span><input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar equipo, programa o unidad" className="control"/></label><div className="md:col-span-2"><MultiSelect label="Roles" emptyLabel="Todos los roles" value={roleIds} onChange={setRoleIds} options={roleOptions}/></div></div><div className="p-5">{loading?<LoadingState label="Cargando equipos…"/>:error?<ErrorState message={error} onRetry={load}/>:!teams.length?<EmptyState detail="No se encontraron equipos para los filtros seleccionados."/>:<div className="grid gap-5 md:grid-cols-2">{teams.map(team=><article key={team.id} className="rounded-2xl border border-slate-200 p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">{team.sourceId}</h2><p className="mt-1 text-sm font-semibold text-emerald-700">{team.program}</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-800">{team.status}</span></div><p className="mt-4 text-sm text-slate-500">{team.company??"Sin empresa"} · {team.unit??"Sin unidad"}</p><div className="mt-5 border-t border-slate-200 pt-4"><p className="text-sm font-bold">Integrantes ({team.members.length})</p>{team.members.length?team.members.sort((a,b)=>a.role.localeCompare(b.role,"es")||a.name.localeCompare(b.name,"es")).map(member=><div key={`${member.name}-${member.role}`} className="mt-3 flex justify-between gap-4 text-sm"><span>{member.name}</span><span className="font-semibold text-slate-500">{member.role}</span></div>):<p className="mt-3 text-sm text-slate-500">Sin integrantes asignados</p>}</div></article>)}</div>}</div></section>{!loading&&!error&&total>0&&<div className="mt-4 flex justify-end gap-3"><button disabled={page===1} onClick={()=>setPage(value=>value-1)} className="ds-button ds-button-secondary disabled:opacity-40">Anterior</button><span className="py-2 text-sm font-bold">Página {page} de {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)} className="ds-button ds-button-secondary disabled:opacity-40">Siguiente</button></div>}</DirectoryShell>}
