import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { PrismaService } from "../database/prisma.service";

const mappings:Record<string,string>={cycleId:"CICLO",focusAreaId:"AREA_ENFOQUE",levelId:"NIVEL_OBJETIVO",typeId:"TIPO_INICIATIVA",executionAreaId:"AREA_EJECUCION_INICIATIVA",sizeId:"TALLA_INICIATIVA",priorityId:"PRIORIDAD_INICIATIVA",managementTypeId:"TIPO_GESTION_INICIATIVA",statusId:"ESTADO_INICIATIVA",escalationId:"ESCALAMIENTO_INICIATIVA",returnHorizonId:"HORIZONTE_RETORNO",tiCapacityId:"CAPACIDAD_TI",categoryId:"CATEGORIA_INICIATIVA",impactId:"IMPACTO_INICIATIVA"};
const required=["companyId","year","cycleId","focusAreaId","levelId","programId","typeId","sizeId","name","managementTypeId","statusId","impactId"];
type Input=Record<string,unknown>;

@Injectable()
export class InitiativesRepository{
 constructor(private readonly prisma:PrismaService){}
 private text(i:Input,k:string,req=false){const v=typeof i[k]==="string"?(i[k] as string).trim():"";if(req&&!v)throw new BadRequestException(k+" es obligatorio");return v||null}
 private number(i:Input,k:string,req=false){const raw=i[k];if(raw===""||raw===null||raw===undefined){if(req)throw new BadRequestException(k+" es obligatorio");return null}const v=Number(raw);if(!Number.isFinite(v))throw new BadRequestException(k+" debe ser numérico");return v}
 private date(i:Input,k:string){const raw=this.text(i,k);if(!raw)return null;const v=new Date(raw);if(Number.isNaN(v.getTime()))throw new BadRequestException(k+" no es una fecha válida");return v}
 private dto(x:any){const normalized={...x};for(const k of ["sourceId","projectedEconomicBenefit","actualEconomicBenefit","projectedMitigationBenefit","actualMitigationBenefit","annualPotentialBenefit","projectedInvestment","actualInvestment"])if(normalized[k]!==null&&normalized[k]!==undefined)normalized[k]=k==="sourceId"?String(normalized[k]):Number(normalized[k]);return JSON.parse(JSON.stringify(normalized,(_,item)=>typeof item==="bigint"?item.toString():item))}
 private snapshot(value:unknown){return JSON.parse(JSON.stringify(value,(_,item)=>typeof item==="bigint"?item.toString():item)) as Prisma.InputJsonValue}
 private assertTeam(teamId:unknown,teamIds:string[]|null){if(teamIds!==null&&(!teamId||!teamIds.includes(String(teamId))))throw new BadRequestException("El equipo no está permitido para esta cuenta")}
 async options(teamIds:string[]|null=null){const [values,teams,companies,programs,objectives]=await Promise.all([this.prisma.catalogValue.findMany({where:{active:true,catalog:{code:{in:Object.values(mappings)},active:true}},orderBy:[{catalog:{code:"asc"}},{sortOrder:"asc"}],select:{id:true,code:true,name:true,catalog:{select:{code:true}}}}),this.prisma.team.findMany({where:teamIds===null?undefined:{id:{in:teamIds}},select:{id:true,sourceId:true,programId:true},orderBy:{sourceId:"asc"}}),this.prisma.company.findMany({select:{id:true,code:true,name:true},orderBy:{name:"asc"}}),this.prisma.program.findMany({where:{active:true},select:{id:true,code:true,name:true},orderBy:{name:"asc"}}),this.prisma.objective.findMany({where:{isSystemPlaceholder:false,recordStatus:{code:"ACTIVO"},teamId:teamIds===null?undefined:{in:teamIds}},select:{id:true,sourceId:true,objective:true,keyResult:true,teamId:true,year:true,cycleId:true,focusAreaId:true},orderBy:{sourceId:"desc"}})]);return{catalogs:Object.fromEntries([...new Set(Object.values(mappings))].map(code=>[code,values.filter(v=>v.catalog.code===code).map(({catalog:_,...v})=>v)])),teams,companies,programs,objectives:objectives.map(x=>({...x,sourceId:String(x.sourceId)}))}}
 async list(search?:string,year?:number,teamIds:string[]|null=null){if(year!==undefined&&(!Number.isInteger(year)||year<2000||year>2100))throw new BadRequestException("Año inválido");const rows=await this.prisma.initiative.findMany({where:{year,teamId:teamIds===null?undefined:{in:teamIds},OR:search?.trim()?[{name:{contains:search.trim(),mode:"insensitive"}},{release:{contains:search.trim(),mode:"insensitive"}}]:undefined},orderBy:[{year:"desc"},{sourceId:"desc"}],include:{team:{select:{id:true,sourceId:true}},company:{select:{id:true,code:true,name:true}},program:{select:{id:true,code:true,name:true}},cycle:true,focusArea:true,level:true,type:true,executionArea:true,size:true,priority:true,managementType:true,status:true,impact:true,objectiveLink:{select:{id:true,sourceId:true,objective:true,keyResult:true,isSystemPlaceholder:true}}}});return rows.map(x=>this.dto(x))}
 async validate(i:Input,current?:{typeId:string;executionAreaId:string|null;objectiveId:string;returnHorizonId:string|null}){const refs=Object.entries(mappings).filter(([k])=>typeof i[k]==="string"&&(i[k] as string).trim());const values=await this.prisma.catalogValue.findMany({where:{id:{in:refs.map(([k])=>i[k] as string)},active:true},select:{id:true,code:true,catalog:{select:{code:true}}}});if(refs.some(([k,c])=>!values.some(v=>v.id===i[k]&&v.catalog.code===c)))throw new BadRequestException("Uno o más valores no corresponden al catálogo indicado");for(const [field,model] of [["companyId","company"],["programId","program"],["teamId","team"]] as const){const id=this.text(i,field);if(id){const found=await (this.prisma[model] as any).findUnique({where:{id},select:{id:true}});if(!found)throw new BadRequestException(field+" no existe")}}const typeId=i.typeId===undefined?current?.typeId:this.text(i,"typeId"),executionAreaId=i.executionAreaId===undefined?current?.executionAreaId:this.text(i,"executionAreaId"),objectiveId=i.objectiveId===undefined?current?.objectiveId:this.text(i,"objectiveId"),returnHorizonId=i.returnHorizonId===undefined?current?.returnHorizonId:this.text(i,"returnHorizonId");const type=typeId?values.find(v=>v.id===typeId)??await this.prisma.catalogValue.findUnique({where:{id:typeId},select:{id:true,code:true,catalog:{select:{code:true}}}}):null,isInternal=type?.catalog.code==="TIPO_INICIATIVA"&&type.code==="GESTION_INTERNA";if(isInternal&&!executionAreaId)throw new BadRequestException("Área de ejecución es obligatoria para iniciativas de Gestión Interna");if(!isInternal){if(!objectiveId)throw new BadRequestException("Objetivo y resultado clave son obligatorios");if(!returnHorizonId)throw new BadRequestException("Horizonte de retorno es obligatorio");const objective=await this.prisma.objective.findUnique({where:{id:objectiveId},select:{isSystemPlaceholder:true}});if(!objective||objective.isSystemPlaceholder)throw new BadRequestException("Debe seleccionar un objetivo real")};return isInternal}
 private async placeholderObjective(year:number){const systemKey=`NO_APLICA_GESTION_INTERNA_${year}`,existing=await this.prisma.objective.findUnique({where:{systemKey},select:{id:true}});if(existing)return existing.id;const referenceCodes:Record<string,[string,string]>={levelId:["NIVEL_OBJETIVO","CORPORATIVO"],focusAreaId:["AREA_ENFOQUE","ESTRATEGIA_DEL_NEGOCIO"],cycleId:["CICLO","ANUAL"],directionId:["DIRECCION_INDICADOR","DIRECTO"],typeId:["TIPO_OBJETIVO","OUTPUT_ENTREGA"],recordStatusId:["ESTADO_REGISTRO_OBJETIVO","ACTIVO"]};const values=await this.prisma.catalogValue.findMany({where:{active:true,OR:Object.values(referenceCodes).map(([catalog,code])=>({code,catalog:{code}}))},select:{id:true,code:true,catalog:{select:{code:true}}}}),reference=(catalog:string,code:string)=>values.find(value=>value.code===code&&value.catalog.code===catalog)?.id,levelId=reference("NIVEL_OBJETIVO","CORPORATIVO"),focusAreaId=reference("AREA_ENFOQUE","ESTRATEGIA_DEL_NEGOCIO"),cycleId=reference("CICLO","ANUAL"),directionId=reference("DIRECCION_INDICADOR","DIRECTO"),typeId=reference("TIPO_OBJETIVO","OUTPUT_ENTREGA"),recordStatusId=reference("ESTADO_REGISTRO_OBJETIVO","ACTIVO");if(!levelId||!focusAreaId||!cycleId||!directionId||!typeId||!recordStatusId)throw new BadRequestException("No se pudo configurar el objetivo técnico No aplica");const objective=await this.prisma.objective.upsert({where:{systemKey},create:{sourceId:BigInt(-year),year,objective:"NO APLICA – GESTIÓN INTERNA",keyResult:"No aplica",isSystemPlaceholder:true,systemKey,levelId,focusAreaId,cycleId,directionId,typeId,recordStatusId},update:{objective:"NO APLICA – GESTIÓN INTERNA",keyResult:"No aplica",isSystemPlaceholder:true},select:{id:true}});return objective.id}
 private data(i:Input,create:boolean){const d:any={};for(const k of required){if(create||i[k]!==undefined)d[k]=k==="year"?this.number(i,k,true):this.text(i,k,true)}for(const k of ["teamId","release","priorityId","productOwner","manager","technicalLead","accompanimentMilestone","escalationId","returnHorizonId","tiCapacityId","categoryId","executionAreaId","impactDescription","observations","documentationUrl","objectiveId"]){if(create||i[k]!==undefined)d[k]=this.text(i,k)}for(const k of ["executionStart","executionEnd"]){if(create||i[k]!==undefined)d[k]=this.date(i,k)}for(const k of ["projectedEconomicBenefit","actualEconomicBenefit","projectedMitigationBenefit","actualMitigationBenefit","annualPotentialBenefit","projectedInvestment","actualInvestment"]){if(create||i[k]!==undefined)d[k]=this.number(i,k)}if(d.year!==undefined&&(!Number.isInteger(d.year)||d.year<2000||d.year>2100))throw new BadRequestException("Año inválido");if(d.executionStart&&d.executionEnd&&d.executionEnd<d.executionStart)throw new BadRequestException("La fecha final no puede ser anterior a la inicial");return d}
 async create(i:Input,teamIds:string[]|null=null,userId?:string){for(const k of required)if(i[k]===undefined||i[k]==="")throw new BadRequestException(k+" es obligatorio");this.assertTeam(i.teamId,teamIds);const isInternal=await this.validate(i),data=this.data(i,true);data.objectiveId=isInternal?await this.placeholderObjective(Number(data.year)):this.text(i,"objectiveId",true);return this.prisma.$transaction(async tx=>{const m=await tx.initiative.aggregate({_max:{sourceId:true}});const created=await tx.initiative.create({data:{...data,sourceId:(m._max.sourceId??0n)+1n},include:{company:true,program:true,cycle:true,focusArea:true,level:true,type:true,executionArea:true,size:true,managementType:true,status:true,impact:true,team:true,objectiveLink:true}});await tx.audit.create({data:{occurredAt:new Date(),userId,action:"CREATE",entity:"INITIATIVE",recordId:created.id,newValue:this.snapshot(created),result:"OK",origin:"WEB"}});return this.dto(created)},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
 async update(id:string,i:Input,teamIds:string[]|null=null,userId?:string){const current=await this.prisma.initiative.findUnique({where:{id}});if(!current)throw new NotFoundException("No se encontró la iniciativa");this.assertTeam(current.teamId,teamIds);this.assertTeam(i.teamId===undefined?current.teamId:i.teamId,teamIds);const isInternal=await this.validate(i,current),data=this.data(i,false),year=Number(data.year??current.year);if(isInternal)data.objectiveId=await this.placeholderObjective(year);return this.prisma.$transaction(async tx=>{const updated=await tx.initiative.update({where:{id},data,include:{company:true,program:true,cycle:true,focusArea:true,level:true,type:true,executionArea:true,size:true,managementType:true,status:true,impact:true,team:true,objectiveLink:true}});await tx.audit.create({data:{occurredAt:new Date(),userId,action:"UPDATE",entity:"INITIATIVE",recordId:id,oldValue:this.snapshot(current),newValue:this.snapshot(updated),result:"OK",origin:"WEB"}});return this.dto(updated)})}
}
