import{useEffect,useState}from"react";
import{PlayCircle}from"lucide-react";
import{apiUrl,demoHeaders}from"../directory/DirectoryShell";
import{ConfirmationDialog}from"../components/ConfirmationDialog";
type Job={code:string;name:string;description:string;lastRun:{occurredAt:string;result:string|null;newValue:unknown}|null};
export function JobsPage(){
 const[jobs,setJobs]=useState<Job[]>([]),[running,setRunning]=useState(""),[message,setMessage]=useState(""),[pending,setPending]=useState<Job|null>(null),[confirmError,setConfirmError]=useState("");
 async function load(){const response=await fetch(`${apiUrl}/api/jobs/admin`,{headers:demoHeaders});if(!response.ok){setMessage("No se pudieron cargar los procesos.");return}setJobs(await response.json())}
 useEffect(()=>{void load()},[]);
 async function run(){if(!pending)return;setRunning(pending.code);setConfirmError("");try{const response=await fetch(`${apiUrl}/api/jobs/admin/${pending.code}/run`,{method:"POST",headers:demoHeaders});const body=await response.json().catch(()=>({}));if(!response.ok){setConfirmError(body.message??"El proceso falló.");return}setMessage(`Proceso terminado: ${body.updated??body.created??0} registro(s) afectados.`);setPending(null);await load()}finally{setRunning("")}}
 return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl justify-between px-5 py-4"><a href="/" className="font-bold">Mochelab <span className="text-emerald-600">2.0</span></a><a href="/configuracion/auditoria" className="font-bold text-emerald-700">Auditoría</a></div></header><div className="mx-auto max-w-6xl px-5 py-8"><p className="font-bold uppercase tracking-wider text-emerald-700">Administración</p><h1 className="mt-2 text-3xl font-bold">Jobs y procesos</h1><p className="mt-2 text-slate-600">Procesos internos controlados, idempotentes y auditados. Las sincronizaciones externas se configurarán cuando se confirme su fuente definitiva.</p>{message&&<p className="mt-5 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-900">{message}</p>}<section className="mt-6 grid gap-4 md:grid-cols-2">{jobs.map(job=><article key={job.code} className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">{job.name}</h2><p className="mt-2 text-slate-600">{job.description}</p><p className="mt-4 text-sm text-slate-500">{job.lastRun?`Última ejecución: ${new Date(job.lastRun.occurredAt).toLocaleString("es-PE")} · ${job.lastRun.result}`:"Aún no ejecutado"}</p><button disabled={Boolean(running)} onClick={()=>{setConfirmError("");setPending(job)}} className="mt-5 rounded-xl bg-slate-950 px-4 py-2 font-bold text-white disabled:opacity-40">{running===job.code?"Ejecutando…":"Ejecutar ahora"}</button></article>)}</section></div>{pending&&<ConfirmationDialog title="Ejecutar proceso" description="Confirma la ejecución manual del proceso administrativo." icon={<PlayCircle size={20}/>} confirmLabel="Ejecutar ahora" busy={Boolean(running)} error={confirmError} onClose={()=>setPending(null)} onConfirm={()=>void run()}><div className="rounded-xl bg-slate-50 p-4"><strong>{pending.name}</strong><span className="mt-1 block text-sm text-slate-500">Código {pending.code}</span></div><p className="mt-4 text-sm text-slate-700">La ejecución y sus resultados quedarán registrados en Auditoría.</p></ConfirmationDialog>}</main>
}
