import { useCallback, useEffect, useState } from "react";
import { apiUrl, demoHeaders } from "../directory/DirectoryShell";

type Option={id:string;code:string;name:string};
type Options={catalogs:Record<string,Option[]>;teams:{id:string;sourceId:string;program:{name:string}}[]};
type Objective={id:string;sourceId:string;year:number;objective:string;keyResult:string;baseline:number|null;target:number|null;actual:number|null;level:Option;focusArea:Option;cycle:Option;direction:Option;type:Option;unit:Option|null;resultStatus:Option|null;recordStatus:Option;team:{id:string;sourceId:string}|null;_count:{children:number;initiatives:number}};
type Form={year:string;levelId:string;teamId:string;focusAreaId:string;cycleId:string;objective:string;keyResult:string;directionId:string;typeId:string;unitId:string;baseline:string;target:string;actual:string;resultStatusId:string;recordStatusId:string};
const blank:Form={year:String(new Date().getFullYear()),levelId:"",teamId:"",focusAreaId:"",cycleId:"",objective:"",keyResult:"",directionId:"",typeId:"",unitId:"",baseline:"",target:"",actual:"",resultStatusId:"",recordStatusId:""};

function Select({label,value,onChange,items,optional=false}:{label:string;value:string;onChange:(v:string)=>void;items:Option[];optional?:boolean}){return <label className="text-sm font-semibold">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-base font-normal"><option value="">{optional?"Ninguno":"Seleccionar"}</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}

export function ObjectivesPage(){
 const [items,setItems]=useState<Objective[]>([]),[options,setOptions]=useState<Options|null>(null),[form,setForm]=useState<Form>(blank),[editing,setEditing]=useState<string|null>(null),[show,setShow]=useState(false),[search,setSearch]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const [a,b]=await Promise.all([fetch(apiUrl+"/api/objectives?search="+encodeURIComponent(search),{headers:demoHeaders}),fetch(apiUrl+"/api/objectives/options",{headers:demoHeaders})]);if(!a.ok||!b.ok)throw new Error("No se pudo cargar la gestión de objetivos");const opts=await b.json() as Options;setItems(await a.json());setOptions(opts);setForm(current=>({...current,recordStatusId:current.recordStatusId||opts.catalogs.ESTADO_REGISTRO_OBJETIVO?.[0]?.id||""}))}catch(e){setMessage(e instanceof Error?e.message:"Error inesperado")}finally{setBusy(false)}},[search]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer)},[load]);
 const set=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
 const catalogs=options?.catalogs??{};
 const valid=["year","levelId","focusAreaId","cycleId","objective","keyResult","directionId","typeId","recordStatusId"].every(key=>form[key as keyof Form].trim());
 function beginCreate(){setEditing(null);setForm({...blank,recordStatusId:catalogs.ESTADO_REGISTRO_OBJETIVO?.[0]?.id||""});setShow(true);setMessage("")}
 function beginEdit(item:Objective){setEditing(item.id);setForm({...blank,year:String(item.year),levelId:item.level.id,teamId:item.team?.id||"",focusAreaId:item.focusArea.id,cycleId:item.cycle.id,objective:item.objective,keyResult:item.keyResult,directionId:item.direction.id,typeId:item.type.id,unitId:item.unit?.id||"",baseline:item.baseline===null?"":String(item.baseline),target:item.target===null?"":String(item.target),actual:item.actual===null?"":String(item.actual),resultStatusId:item.resultStatus?.id||"",recordStatusId:item.recordStatus.id});setShow(true)}
 async function save(){setBusy(true);const r=await fetch(apiUrl+"/api/objectives"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(typeof body.message==="string"?body.message:"No se pudo guardar el objetivo");setBusy(false);return}setMessage(editing?"Objetivo actualizado correctamente.":"Objetivo y resultado clave registrados.");setShow(false);await load()}
 return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="/" className="text-lg font-bold">Mochelab <span className="text-emerald-600">2.0</span></a><span className="rounded-full bg-slate-900 px-3 py-1 text-sm font-semibold text-white">Gestión de objetivos</span></div></header>
 <div className="mx-auto max-w-7xl px-5 py-8"><div className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-7 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Ejecución estratégica</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Objetivos y resultados clave</h1><p className="mt-3 text-base text-slate-600">Registra el objetivo, su resultado medible y el avance acumulado.</p></div><button onClick={beginCreate} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white">Nuevo objetivo</button></div>
 <label className="mt-6 block text-sm font-semibold">Buscar objetivo o resultado clave<input value={search} onChange={e=>setSearch(e.target.value)} className="mt-2 block w-full max-w-xl rounded-xl border border-slate-300 bg-white px-4 py-3 text-base" placeholder="Escribe para filtrar"/></label>
 {show&&options&&<section className="mt-6 rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?"Editar objetivo":"Nuevo objetivo"}</h2><button onClick={()=>setShow(false)} className="text-sm font-bold text-slate-500">Cerrar</button></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">Año<input type="number" value={form.year} onChange={e=>set("year",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label><Select label="Nivel" value={form.levelId} onChange={v=>set("levelId",v)} items={catalogs.NIVEL_OBJETIVO??[]}/><Select label="Ciclo" value={form.cycleId} onChange={v=>set("cycleId",v)} items={catalogs.CICLO??[]}/><Select label="Área de enfoque" value={form.focusAreaId} onChange={v=>set("focusAreaId",v)} items={catalogs.AREA_ENFOQUE??[]}/><Select label="Tipo" value={form.typeId} onChange={v=>set("typeId",v)} items={catalogs.TIPO_OBJETIVO??[]}/><Select label="Dirección" value={form.directionId} onChange={v=>set("directionId",v)} items={catalogs.DIRECCION_INDICADOR??[]}/><label className="text-sm font-semibold">Equipo<select value={form.teamId} onChange={e=>set("teamId",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-base font-normal"><option value="">Sin equipo</option>{options.teams.map(x=><option key={x.id} value={x.id}>{x.sourceId} · {x.program.name}</option>)}</select></label></div>
 <div className="mt-4 grid gap-4"><label className="text-sm font-semibold">Objetivo<textarea value={form.objective} onChange={e=>set("objective",e.target.value)} rows={2} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label><label className="text-sm font-semibold">Resultado clave<textarea value={form.keyResult} onChange={e=>set("keyResult",e.target.value)} rows={2} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label></div>
 <div className="mt-4 grid gap-4 md:grid-cols-4"><Select label="Unidad" value={form.unitId} onChange={v=>set("unitId",v)} items={catalogs.UNIDAD_KR??[]} optional/>{(["baseline","target","actual"] as const).map(key=><label key={key} className="text-sm font-semibold">{key==="baseline"?"Línea base":key==="target"?"Meta":"Valor actual"}<input type="number" step="any" value={form[key]} onChange={e=>set(key,e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label>)}<Select label="Resultado" value={form.resultStatusId} onChange={v=>set("resultStatusId",v)} items={catalogs.ESTADO_RESULTADO_CLAVE??[]} optional/><Select label="Estado" value={form.recordStatusId} onChange={v=>set("recordStatusId",v)} items={catalogs.ESTADO_REGISTRO_OBJETIVO??[]}/></div><div className="mt-5 flex justify-end"><button disabled={!valid||busy} onClick={save} className="rounded-xl bg-emerald-600 px-6 py-3 text-sm font-bold text-white disabled:bg-slate-300">Guardar</button></div></section>}
 {message&&<p role="status" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900">{message}</p>}
 <div className="mt-7 space-y-4">{busy&&!items.length&&<p>Cargando…</p>}{!busy&&!items.length&&<p className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600">No hay objetivos para mostrar.</p>}{items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-sm font-semibold text-emerald-700">#{item.sourceId} · {item.year} · {item.cycle.name}</p><h2 className="mt-2 text-xl font-bold">{item.objective}</h2><p className="mt-3 text-slate-700"><span className="font-semibold">KR:</span> {item.keyResult}</p></div><button onClick={()=>beginEdit(item)} className="self-start rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold">Editar</button></div><dl className="mt-5 grid gap-4 border-t border-slate-200 pt-5 sm:grid-cols-4"><div><dt className="text-sm text-slate-500">Nivel / equipo</dt><dd className="font-semibold">{item.level.name}{item.team?" · "+item.team.sourceId:""}</dd></div><div><dt className="text-sm text-slate-500">Área</dt><dd className="font-semibold">{item.focusArea.name}</dd></div><div><dt className="text-sm text-slate-500">Base → meta → actual</dt><dd className="font-semibold">{item.baseline??"—"} → {item.target??"—"} → {item.actual??"—"} {item.unit?.name??""}</dd></div><div><dt className="text-sm text-slate-500">Relaciones</dt><dd className="font-semibold">{item._count.children} objetivo(s) · {item._count.initiatives} iniciativa(s)</dd></div></dl></article>)}</div>
 </div></main>
}
