import { useCallback, useEffect, useState } from "react";
import { apiUrl, demoHeaders } from "../directory/DirectoryShell";
import { useModuleCapability } from "../access/useModuleCapability";
import { MultiSelect } from "../components/MultiSelect";
import { SlidersHorizontal } from "lucide-react";

type Option={id:string;code:string;name:string};
type Options={catalogs:Record<string,Option[]>;teams:{id:string;sourceId:string;program:{name:string}}[];parents:{id:string;sourceId:string;objective:string}[]};
type Objective={id:string;sourceId:string;year:number;objective:string;keyResult:string;baseline:number|null;baselineDate:string|null;target:number|null;actual:number|null;cutoffDate:string|null;achievement:number|null;level:Option;focusArea:Option;cycle:Option;direction:Option;type:Option;unit:Option|null;resultStatus:Option|null;recordStatus:Option;team:{id:string;sourceId:string}|null;parent:{id:string;sourceId:string;objective:string}|null;_count:{children:number;initiatives:number}};
type Form={year:string;levelId:string;parentId:string;teamId:string;focusAreaId:string;cycleId:string;objective:string;keyResult:string;directionId:string;typeId:string;unitId:string;baseline:string;baselineDate:string;target:string;actual:string;cutoffDate:string;resultStatusId:string;recordStatusId:string};
const blank:Form={year:String(new Date().getFullYear()),levelId:"",parentId:"",teamId:"",focusAreaId:"",cycleId:"",objective:"",keyResult:"",directionId:"",typeId:"",unitId:"",baseline:"",baselineDate:"",target:"",actual:"",cutoffDate:"",resultStatusId:"",recordStatusId:""};

function Select({label,value,onChange,items,optional=false}:{label:string;value:string;onChange:(v:string)=>void;items:Option[];optional?:boolean}){return <label className="text-sm font-semibold">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-base font-normal"><option value="">{optional?"Ninguno":"Seleccionar"}</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
function exportObjectives(items:Objective[]){const rows=[["ID","Año","Nivel","Equipo","Área","Ciclo","Objetivo","Resultado clave","Línea base","Meta","Actual","Cumplimiento","Estado"],...items.map(x=>[x.sourceId,x.year,x.level.name,x.team?.sourceId??"Corporativo",x.focusArea.name,x.cycle.name,x.objective,x.keyResult,x.baseline??"",x.target??"",x.actual??"",x.achievement??"",x.resultStatus?.name??""])];const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="objetivos-okr.csv";a.click();URL.revokeObjectURL(a.href)}

export function ObjectivesPage(){
 const capability=useModuleCapability("OBJETIVOS");
 const [items,setItems]=useState<Objective[]>([]),[options,setOptions]=useState<Options|null>(null),[form,setForm]=useState<Form>(blank),[editing,setEditing]=useState<string|null>(null),[show,setShow]=useState(false),[search,setSearch]=useState(""),[year,setYear]=useState(String(new Date().getFullYear())),[teamFilter,setTeamFilter]=useState<string[]>([]),[levelFilter,setLevelFilter]=useState<string[]>([]),[cycleFilter,setCycleFilter]=useState<string[]>([]),[statusFilter,setStatusFilter]=useState<string[]>([]),[filtersOpen,setFiltersOpen]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[page,setPage]=useState(1);const pageSize=10;
 const load=useCallback(async()=>{setBusy(true);try{const q=new URLSearchParams({search,year});const [a,b]=await Promise.all([fetch(apiUrl+"/api/objectives?"+q,{headers:demoHeaders}),fetch(apiUrl+"/api/objectives/options",{headers:demoHeaders})]);if(!a.ok||!b.ok)throw new Error("No se pudo cargar la gestión de objetivos");const opts=await b.json() as Options;setItems(await a.json());setOptions(opts);setForm(current=>({...current,recordStatusId:current.recordStatusId||opts.catalogs.ESTADO_REGISTRO_OBJETIVO?.[0]?.id||""}))}catch(e){setMessage(e instanceof Error?e.message:"Error inesperado")}finally{setBusy(false)}},[search,year]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer)},[load]);
 useEffect(()=>setPage(1),[search,year,teamFilter,levelFilter,cycleFilter,statusFilter]);
 const set=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
 const catalogs=options?.catalogs??{};
 const valid=["year","levelId","focusAreaId","cycleId","objective","keyResult","directionId","typeId","recordStatusId"].every(key=>form[key as keyof Form].trim());
 function beginCreate(){if(!capability?.canCreate){setMessage("Tu perfil no tiene permiso para crear objetivos.");return}setEditing(null);setForm({...blank,recordStatusId:catalogs.ESTADO_REGISTRO_OBJETIVO?.[0]?.id||""});setShow(true);setMessage("")}
 function beginEdit(item:Objective){if(!capability?.canEdit){setMessage("Tu perfil no tiene permiso para editar objetivos.");return}setEditing(item.id);setForm({...blank,year:String(item.year),levelId:item.level.id,parentId:item.parent?.id||"",teamId:item.team?.id||"",focusAreaId:item.focusArea.id,cycleId:item.cycle.id,objective:item.objective,keyResult:item.keyResult,directionId:item.direction.id,typeId:item.type.id,unitId:item.unit?.id||"",baseline:item.baseline===null?"":String(item.baseline),baselineDate:item.baselineDate?.slice(0,10)||"",target:item.target===null?"":String(item.target),actual:item.actual===null?"":String(item.actual),cutoffDate:item.cutoffDate?.slice(0,10)||"",resultStatusId:item.resultStatus?.id||"",recordStatusId:item.recordStatus.id});setShow(true)}
 async function save(){setBusy(true);const r=await fetch(apiUrl+"/api/objectives"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(typeof body.message==="string"?body.message:"No se pudo guardar el objetivo");setBusy(false);return}setMessage(editing?"Objetivo actualizado correctamente.":"Objetivo y resultado clave registrados.");setShow(false);await load()}
 const filtered=items.filter(item=>(!teamFilter.length||(teamFilter.includes("CORPORATIVO")&&!item.team)||Boolean(item.team&&teamFilter.includes(item.team.id)))&&(!levelFilter.length||levelFilter.includes(item.level.id))&&(!cycleFilter.length||cycleFilter.includes(item.cycle.id))&&(!statusFilter.length||statusFilter.includes(item.recordStatus.id)));
 return <main className="min-h-screen bg-slate-100 text-slate-950">
 <div className="mx-auto max-w-7xl px-5 py-8"><div className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-7 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Ejecución estratégica</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Objetivos y resultados clave</h1><p className="mt-3 text-base text-slate-600">Registra el objetivo, su resultado medible y el avance acumulado.</p></div><div className="flex gap-2"><button onClick={()=>exportObjectives(filtered)} className="rounded-xl border border-emerald-600 px-5 py-3 text-sm font-bold text-emerald-700">Exportar</button><button onClick={beginCreate} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white">Nuevo objetivo</button></div></div>
 <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={()=>setFiltersOpen(!filtersOpen)} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold"><SlidersHorizontal size={16}/>Filtros{(teamFilter.length+levelFilter.length+cycleFilter.length+statusFilter.length+(search?1:0))>0&&<span className="rounded-full bg-red-50 px-2 py-0.5 text-xs text-red-700">{teamFilter.length+levelFilter.length+cycleFilter.length+statusFilter.length+(search?1:0)}</span>}</button><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">Año: {year}</span>{(teamFilter.length+levelFilter.length+cycleFilter.length+statusFilter.length+(search?1:0))>0&&<button type="button" onClick={()=>{setSearch("");setTeamFilter([]);setLevelFilter([]);setCycleFilter([]);setStatusFilter([])}} className="text-sm font-bold text-red-700">Limpiar filtros</button>}</div>{filtersOpen&&<div className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-3 lg:grid-cols-6"><input value={search} onChange={e=>setSearch(e.target.value)} className="control md:col-span-2" placeholder="Objetivo o resultado clave"/><input type="number" value={year} onChange={e=>setYear(e.target.value)} className="control" placeholder="Todos los años"/><MultiSelect label="Alcances" emptyLabel="Todos los alcances" value={teamFilter} onChange={setTeamFilter} options={[{id:"CORPORATIVO",label:"Corporativo"},...(options?.teams??[]).map(item=>({id:item.id,label:item.sourceId}))]}/><MultiSelect label="Niveles" emptyLabel="Todos los niveles" value={levelFilter} onChange={setLevelFilter} options={(catalogs.NIVEL_OBJETIVO??[]).map(item=>({id:item.id,label:item.name}))}/><MultiSelect label="Ciclos" emptyLabel="Todos los ciclos" value={cycleFilter} onChange={setCycleFilter} options={(catalogs.CICLO??[]).map(item=>({id:item.id,label:item.name}))}/><MultiSelect label="Estados" emptyLabel="Todos los estados" value={statusFilter} onChange={setStatusFilter} options={(catalogs.ESTADO_REGISTRO_OBJETIVO??[]).map(item=>({id:item.id,label:item.name}))}/></div>}</section>
 <section className="mt-6 grid gap-4 sm:grid-cols-4"><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Objetivos filtrados</p><strong className="text-2xl">{filtered.length}</strong></article><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Cumplimiento promedio</p><strong className="text-2xl">{filtered.length?Math.round(filtered.reduce((n,x)=>n+(x.achievement??0),0)/filtered.length):0}%</strong></article><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Corporativos</p><strong className="text-2xl">{filtered.filter(x=>!x.team).length}</strong></article><article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Iniciativas relacionadas</p><strong className="text-2xl">{filtered.reduce((n,x)=>n+x._count.initiatives,0)}</strong></article></section>
 {show&&options&&<section className="mt-6 rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?"Editar objetivo":"Nuevo objetivo"}</h2><button onClick={()=>setShow(false)} className="text-sm font-bold text-slate-500">Cerrar</button></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">Año<input type="number" value={form.year} onChange={e=>set("year",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label><Select label="Nivel" value={form.levelId} onChange={v=>set("levelId",v)} items={catalogs.NIVEL_OBJETIVO??[]}/><Select label="Ciclo" value={form.cycleId} onChange={v=>set("cycleId",v)} items={catalogs.CICLO??[]}/><Select label="Área de enfoque" value={form.focusAreaId} onChange={v=>set("focusAreaId",v)} items={catalogs.AREA_ENFOQUE??[]}/><Select label="Tipo" value={form.typeId} onChange={v=>set("typeId",v)} items={catalogs.TIPO_OBJETIVO??[]}/><Select label="Dirección" value={form.directionId} onChange={v=>set("directionId",v)} items={catalogs.DIRECCION_INDICADOR??[]}/><label className="text-sm font-semibold">Equipo<select value={form.teamId} onChange={e=>set("teamId",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-base font-normal"><option value="">Sin equipo</option>{options.teams.map(x=><option key={x.id} value={x.id}>{x.sourceId} · {x.program.name}</option>)}</select></label></div>
 <div className="mt-4 grid gap-4"><label className="text-sm font-semibold">Objetivo padre<select value={form.parentId} onChange={e=>set("parentId",e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-3 py-3 text-base font-normal"><option value="">Sin objetivo padre</option>{options.parents.filter(x=>x.id!==editing).map(x=><option key={x.id} value={x.id}>#{x.sourceId} · {x.objective}</option>)}</select></label><label className="text-sm font-semibold">Objetivo<textarea value={form.objective} onChange={e=>set("objective",e.target.value)} rows={2} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label><label className="text-sm font-semibold">Resultado clave<textarea value={form.keyResult} onChange={e=>set("keyResult",e.target.value)} rows={2} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label></div>
 <div className="mt-4 grid gap-4 md:grid-cols-4"><Select label="Unidad" value={form.unitId} onChange={v=>set("unitId",v)} items={catalogs.UNIDAD_KR??[]} optional/>{(["baseline","target","actual"] as const).map(key=><label key={key} className="text-sm font-semibold">{key==="baseline"?"Línea base":key==="target"?"Meta":"Valor actual"}<input type="number" step="any" value={form[key]} onChange={e=>set(key,e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label>)}<Select label="Resultado" value={form.resultStatusId} onChange={v=>set("resultStatusId",v)} items={catalogs.ESTADO_RESULTADO_CLAVE??[]} optional/><Select label="Estado" value={form.recordStatusId} onChange={v=>set("recordStatusId",v)} items={catalogs.ESTADO_REGISTRO_OBJETIVO??[]}/></div><div className="mt-5 flex justify-end"><button disabled={!valid||busy} onClick={save} className="rounded-xl bg-emerald-600 px-6 py-3 text-sm font-bold text-white disabled:bg-slate-300">Guardar</button></div></section>}
 {show&&<section className="mt-4 rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">Fechas de medición</h3><p className="mt-1 text-sm text-slate-500">Registra cuándo se estableció la línea base y la fecha del último valor ejecutado.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Fecha de línea base<input type="date" value={form.baselineDate} onChange={e=>set("baselineDate",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label><label className="text-sm font-semibold">Fecha de corte<input type="date" value={form.cutoffDate} onChange={e=>set("cutoffDate",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-normal"/></label></div></section>}
 {capability&&!capability.canCreate&&!capability.canEdit&&<p className="mt-5 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-900">Tu perfil tiene acceso de consulta. Las acciones de creación y edición están deshabilitadas.</p>}
 {message&&<p role="status" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900">{message}</p>}
 <div className="mt-7 space-y-4">{busy&&!items.length&&<p>Cargando…</p>}{!busy&&!filtered.length&&<p className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600">No hay objetivos para los filtros seleccionados.</p>}{filtered.slice((page-1)*pageSize,page*pageSize).map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-sm font-semibold text-emerald-700">#{item.sourceId} · {item.year} · {item.cycle.name}</p><h2 className="mt-2 text-xl font-bold">{item.objective}</h2><p className="mt-3 text-slate-700"><span className="font-semibold">KR:</span> {item.keyResult}</p>{item.parent&&<p className="mt-2 text-sm text-slate-500"><strong>Depende de:</strong> #{item.parent.sourceId} · {item.parent.objective}</p>}</div><div className="flex gap-2">{item._count.initiatives>0&&<a href={`/portafolio?objectiveId=${item.id}`} className="self-start rounded-xl border border-emerald-600 px-4 py-2 text-sm font-bold text-emerald-700">Ver iniciativas</a>}<button onClick={()=>beginEdit(item)} className="self-start rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold">Editar</button></div></div><dl className="mt-5 grid gap-4 border-t border-slate-200 pt-5 sm:grid-cols-4"><div><dt className="text-sm text-slate-500">Nivel / equipo</dt><dd className="font-semibold">{item.level.name}{item.team?" · "+item.team.sourceId:""}</dd></div><div><dt className="text-sm text-slate-500">Área</dt><dd className="font-semibold">{item.focusArea.name}</dd></div><div><dt className="text-sm text-slate-500">Base → meta → actual</dt><dd className="font-semibold">{item.baseline??"—"} → {item.target??"—"} → {item.actual??"—"} {item.unit?.name??""}</dd></div><div><dt className="text-sm text-slate-500">Relaciones</dt><dd className="font-semibold">{item._count.children} objetivo(s) · {item._count.initiatives} iniciativa(s)</dd></div></dl></article>)}</div><Pager page={page} total={filtered.length} pageSize={pageSize} setPage={setPage}/>
 </div></main>
}
function Pager({page,total,pageSize,setPage}:{page:number;total:number;pageSize:number;setPage:(value:number)=>void}){const pages=Math.max(1,Math.ceil(total/pageSize));return <div className="mt-4 flex justify-end gap-3"><button disabled={page===1} onClick={()=>setPage(page-1)} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Anterior</button><span className="py-2 text-sm font-bold">Página {page} de {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Siguiente</button></div>}
