import { useEffect,useState } from "react";
import { apiUrl,demoHeaders } from "../directory/DirectoryShell";

type O={id:string;code:string;name:string};
type Options={catalogs:Record<string,O[]>;teams:{id:string;sourceId:string}[];roles:{id:string;sourceId:string;name:string}[]};
type Row={id:string;indicator:O;scope:O;team:{id:string;sourceId:string}|null;role:{id:string;sourceId:string;name:string}|null;validFrom:string;validUntil:string|null;target:number;unit:O;status:O};
type Form={indicatorId:string;scopeId:string;teamId:string;roleId:string;validFrom:string;validUntil:string;target:string;unitId:string;statusId:string};
const blank:Form={indicatorId:"",scopeId:"",teamId:"",roleId:"",validFrom:"",validUntil:"",target:"",unitId:"",statusId:""};
const field="mt-2 w-full rounded-xl border bg-white px-3 py-3 text-base font-normal";
function S({label,value,set,items}:{label:string;value:string;set:(v:string)=>void;items:O[]}){return <label className="text-sm font-semibold">{label}<select value={value} onChange={e=>set(e.target.value)} className={field}><option value="">Seleccionar</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}

export function TargetsPage(){
 const[rows,setRows]=useState<Row[]>([]),[opts,setOpts]=useState<Options|null>(null),[form,setForm]=useState<Form>(blank),[editing,setEditing]=useState<string|null>(null),[show,setShow]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const[a,b]=await Promise.all([fetch(apiUrl+"/api/targets",{headers:demoHeaders}),fetch(apiUrl+"/api/targets/options",{headers:demoHeaders})]);if(!a.ok||!b.ok){setMessage("No se pudieron cargar las metas.");return}setRows(await a.json());setOpts(await b.json())}
 useEffect(()=>{void load()},[]);
 const set=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
 function create(){setEditing(null);setForm(blank);setShow(true)}
 function edit(row:Row){setEditing(row.id);setForm({indicatorId:row.indicator.id,scopeId:row.scope.id,teamId:row.team?.id||"",roleId:row.role?.id||"",validFrom:row.validFrom.slice(0,10),validUntil:row.validUntil?.slice(0,10)||"",target:String(row.target),unitId:row.unit.id,statusId:row.status.id});setShow(true)}
 async function save(){setBusy(true);const response=await fetch(apiUrl+"/api/targets"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",headers:{...demoHeaders,"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json().catch(()=>({}));if(!response.ok){setMessage(body.message??"No se pudo guardar la meta");setBusy(false);return}setMessage(editing?"Meta actualizada.":"Meta registrada.");setShow(false);await load();setBusy(false)}
 const catalogs=opts?.catalogs??{},valid=form.indicatorId&&form.scopeId&&form.validFrom&&form.target&&form.unitId&&form.statusId;
 return <main className="min-h-screen bg-slate-100"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl justify-between px-5 py-4"><a href="/" className="text-lg font-bold">Mochelab <span className="text-emerald-600">2.0</span></a><a href="/objetivos" className="text-sm font-bold text-emerald-700">Objetivos</a></div></header><div className="mx-auto max-w-6xl px-5 py-8">
  <div className="flex flex-col gap-5 border-b pb-7 sm:flex-row sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Objetivos</p><h1 className="mt-2 text-3xl font-bold">Metas e indicadores</h1><p className="mt-3 text-slate-600">Define valores objetivo y su vigencia para cada indicador.</p></div><button onClick={create} className="w-full self-end rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white sm:w-auto">Nueva meta</button></div>
  {message&&<p className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold">{message}</p>}
  {show&&opts&&<section className="mt-6 rounded-2xl border border-emerald-200 bg-white p-6"><div className="grid gap-4 sm:grid-cols-3"><S label="Indicador" value={form.indicatorId} set={v=>set("indicatorId",v)} items={catalogs.INDICADOR_META??[]}/><S label="Alcance" value={form.scopeId} set={v=>set("scopeId",v)} items={catalogs.ALCANCE_META??[]}/><S label="Unidad" value={form.unitId} set={v=>set("unitId",v)} items={catalogs.UNIDAD_META??[]}/><label className="text-sm font-semibold">Equipo<select value={form.teamId} onChange={e=>set("teamId",e.target.value)} className={field}><option value="">Ninguno</option>{opts.teams.map(x=><option key={x.id} value={x.id}>{x.sourceId}</option>)}</select></label><label className="text-sm font-semibold">Rol<select value={form.roleId} onChange={e=>set("roleId",e.target.value)} className={field}><option value="">Ninguno</option>{opts.roles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><S label="Estado" value={form.statusId} set={v=>set("statusId",v)} items={catalogs.ESTADO_META??[]}/><label className="text-sm font-semibold">Desde<input type="date" value={form.validFrom} onChange={e=>set("validFrom",e.target.value)} className={field}/></label><label className="text-sm font-semibold">Hasta<input type="date" value={form.validUntil} onChange={e=>set("validUntil",e.target.value)} className={field}/></label><label className="text-sm font-semibold">Valor meta<input type="number" step="any" value={form.target} onChange={e=>set("target",e.target.value)} className={field}/></label></div><div className="mt-5 flex justify-end gap-3"><button onClick={()=>setShow(false)} className="px-4 py-3 font-bold text-slate-500">Cancelar</button><button disabled={!valid||busy} onClick={save} className="rounded-xl bg-emerald-600 px-6 py-3 text-sm font-bold text-white disabled:bg-slate-300">Guardar</button></div></section>}
  <section className="mt-7 overflow-hidden rounded-2xl border bg-white"><div className="divide-y sm:hidden">{rows.map(row=><article key={row.id} className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="min-w-0 break-words font-bold">{row.indicator.name}</h2><span className="shrink-0 rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{row.status.name}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs font-bold uppercase text-slate-400">Alcance</dt><dd className="mt-1">{row.scope.name}{row.team?" · "+row.team.sourceId:""}{row.role?" · "+row.role.name:""}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Meta</dt><dd className="mt-1 font-bold">{row.target} {row.unit.name}</dd></div><div className="col-span-2"><dt className="text-xs font-bold uppercase text-slate-400">Vigencia</dt><dd className="mt-1">{row.validFrom.slice(0,10)} → {row.validUntil?.slice(0,10)||"Sin fin"}</dd></div></dl><button onClick={()=>edit(row)} className="mt-4 w-full rounded-xl border px-4 py-2.5 text-sm font-bold">Editar</button></article>)}</div><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50"><tr><th className="px-5 py-4">Indicador</th><th className="px-5 py-4">Alcance</th><th className="px-5 py-4">Vigencia</th><th className="px-5 py-4">Meta</th><th className="px-5 py-4">Estado</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="px-5 py-4 font-semibold">{row.indicator.name}</td><td className="px-5 py-4">{row.scope.name}{row.team?" · "+row.team.sourceId:""}{row.role?" · "+row.role.name:""}</td><td className="px-5 py-4">{row.validFrom.slice(0,10)} → {row.validUntil?.slice(0,10)||"Sin fin"}</td><td className="px-5 py-4 font-bold">{row.target} {row.unit.name}</td><td className="px-5 py-4">{row.status.name}</td><td className="px-5 py-4"><button onClick={()=>edit(row)} className="rounded-lg border px-3 py-2 text-sm font-bold">Editar</button></td></tr>)}</tbody></table></div></section>
 </div></main>
}
