import { randomUUID } from "node:crypto";import { BadRequestException,Injectable,NotFoundException } from "@nestjs/common";import { Prisma } from "@prisma/client";import { PrismaService } from "../database/prisma.service";
const refs:Record<string,string>={indicatorId:"INDICADOR_META",scopeId:"ALCANCE_META",unitId:"UNIDAD_META",statusId:"ESTADO_META"};
@Injectable()
export class TargetsRepository{constructor(private readonly prisma:PrismaService){}private snap(v:unknown){return JSON.parse(JSON.stringify(v)) as Prisma.InputJsonValue}private date(v:unknown,required=false){if(!v){if(required)throw new BadRequestException("La fecha inicial es obligatoria");return null}const d=new Date(String(v));if(Number.isNaN(d.getTime()))throw new BadRequestException("Fecha inválida");return d}private assertTeam(teamId:unknown,teamIds:string[]|null){if(teamIds!==null&&(!teamId||!teamIds.includes(String(teamId))))throw new BadRequestException("El equipo no está permitido para esta cuenta")}async options(teamIds:string[]|null=null){const [values,teams,roles]=await Promise.all([this.prisma.catalogValue.findMany({where:{active:true,catalog:{code:{in:Object.values(refs)}}},orderBy:[{catalog:{code:"asc"}},{sortOrder:"asc"}],select:{id:true,code:true,name:true,catalog:{select:{code:true}}}}),this.prisma.team.findMany({where:teamIds===null?undefined:{id:{in:teamIds}},orderBy:{sourceId:"asc"},select:{id:true,sourceId:true}}),this.prisma.role.findMany({where:{status:{code:"ACTIVO"}},orderBy:{name:"asc"},select:{id:true,sourceId:true,name:true}})]);return{catalogs:Object.fromEntries(Object.values(refs).map(code=>[code,values.filter(x=>x.catalog.code===code).map(({catalog:_,...x})=>x)])),teams,roles}}
 async list(teamIds:string[]|null=null){const rows=await this.prisma.indicatorTarget.findMany({where:{teamId:teamIds===null?undefined:{in:teamIds}},orderBy:[{validFrom:"desc"},{sourceId:"asc"}],include:{indicator:true,scope:true,team:{select:{id:true,sourceId:true}},role:{select:{id:true,sourceId:true,name:true}},unit:true,status:true}});return rows.map(x=>({...x,target:Number(x.target)}))}
 async validate(i:Record<string,unknown>){const pairs=Object.entries(refs);const values=await this.prisma.catalogValue.findMany({where:{id:{in:pairs.map(([k])=>String(i[k]||""))}},select:{id:true,catalog:{select:{code:true}}}});if(pairs.some(([k,c])=>!values.some(v=>v.id===i[k]&&v.catalog.code===c)))throw new BadRequestException("Indicador, alcance, unidad o estado inválido");for(const [field,model] of [["teamId","team"],["roleId","role"]] as const){if(i[field]&&!await (this.prisma[model] as any).findUnique({where:{id:String(i[field])},select:{id:true}}))throw new BadRequestException(field+" inválido")}}
 private data(i:Record<string,unknown>,create:boolean){const d:any={};for(const k of Object.keys(refs)){if(create||i[k]!==undefined){const v=String(i[k]||"");if(!v)throw new BadRequestException(k+" es obligatorio");d[k]=v}}for(const k of ["teamId","roleId"]){if(create||i[k]!==undefined)d[k]=i[k]?String(i[k]):null}if(create||i.validFrom!==undefined)d.validFrom=this.date(i.validFrom,true);if(create||i.validUntil!==undefined)d.validUntil=this.date(i.validUntil);if(create||i.target!==undefined){const n=Number(i.target);if(!Number.isFinite(n))throw new BadRequestException("La meta debe ser numérica");d.target=n}if(d.validFrom&&d.validUntil&&d.validUntil<d.validFrom)throw new BadRequestException("La vigencia final no puede ser anterior a la inicial");return d}
 async create(i:Record<string,unknown>,teamIds:string[]|null=null,userId?:string){this.assertTeam(i.teamId,teamIds);await this.validate(i);const data=this.data(i,true);return this.prisma.$transaction(async tx=>{const row=await tx.indicatorTarget.create({data:{...data,sourceId:"META-"+randomUUID()},include:{indicator:true,scope:true,team:true,role:true,unit:true,status:true}});await tx.audit.create({data:{occurredAt:new Date(),userId,action:"CREATE",entity:"INDICATOR_TARGET",recordId:row.id,newValue:this.snap(row),result:"OK",origin:"WEB"}});return{...row,target:Number(row.target)}})}
 async update(id:string,i:Record<string,unknown>,teamIds:string[]|null=null,userId?:string){const current=await this.prisma.indicatorTarget.findUnique({where:{id}});if(!current)throw new NotFoundException("No se encontró la meta");this.assertTeam(current.teamId,teamIds);this.assertTeam(i.teamId===undefined?current.teamId:i.teamId,teamIds);await this.validate({...current,...i});return this.prisma.$transaction(async tx=>{const row=await tx.indicatorTarget.update({where:{id},data:this.data(i,false),include:{indicator:true,scope:true,team:true,role:true,unit:true,status:true}});await tx.audit.create({data:{occurredAt:new Date(),userId,action:"UPDATE",entity:"INDICATOR_TARGET",recordId:id,oldValue:this.snap(current),newValue:this.snap(row),result:"OK",origin:"WEB"}});return{...row,target:Number(row.target)}})}}
